#######################################################
# 
# StrategyGestisciDipendenti.py
# Python implementation of the Class StrategyGestisciDipendenti
# Generated by Enterprise Architect
# Created on:      16-ott-2022 00:40:54
# Original author: Valerio Morelli
# 
#######################################################
from frontend.controller.amministrazione.strategy_dipendenti.StrategyDipendenti import StrategyDipendenti


class StrategyGestisciDipendenti(StrategyDipendenti):
    def initializeUi(self, c: 'ControllerGestioneDipendenti') -> None:
        c.view.getHeaderLabel().setText('HomeAmministrazione ➜ GestisciDipendenti')
        c.view.getAssumiButton().setVisible(True)
        c.view.setMaximumHeight(780)

    def initializeWidgetUi(self, c: 'ControllerWidgetDipendente') -> None:
        c.view.getLicenziaButton().setVisible(True)
        c.view.getPromuoviButton().setVisible(True)
        c.view.getSelezionaButton().setVisible(False)
        c.view.getOccupatoLabel().setVisible(False)
