#######################################################
# 
# StrategyDipendenti.py
# Python implementation of the Interface StrategyDipendenti
# Generated by Enterprise Architect
# Created on:      16-ott-2022 00:40:54
# Original author: Valerio Morelli
# 
#######################################################
import abc


class StrategyDipendenti(abc.ABC):
    @abc.abstractmethod
    def initializeUi(self, c: 'ControllerGestioneDipendenti') -> None:
        pass

    @abc.abstractmethod
    def initializeWidgetUi(self, c: 'ControllerWidgetDipendente') -> None:
        pass
