#######################################################
# 
# StrategySelezionaGuida.py
# Python implementation of the Class StrategySelezionaGuida
# Generated by Enterprise Architect
# Created on:      16-ott-2022 00:40:54
# Original author: Valerio Morelli
# 
#######################################################
from backend.high_level.personale.operatore_al_pubblico import OperatoreAlPubblico
from frontend.controller.amministrazione.strategy_dipendenti.StrategyDipendenti import StrategyDipendenti
from frontend.ui.location import UI_DIR


class StrategySelezionaGuida(StrategyDipendenti):
    def initializeUi(self, c: 'ControllerGestioneDipendenti') -> None:
        c.view.getHeaderLabel().setText('ModificaTurnoGuida ➜ SelezionaGuida')
        for controller in c.dipendenti:
            if not isinstance(controller.model.lavoro, OperatoreAlPubblico):
                controller.view.setParent(None)
                c.dipendenti.remove(controller)
        c.view.getAssumiButton().setVisible(False)
        c.view.setMaximumHeight(720)

    def initializeWidgetUi(self, c: 'ControllerWidgetDipendente') -> None:
        c.view.getLicenziaButton().setVisible(False)
        c.view.getPromuoviButton().setVisible(False)
        c.view.getSelezionaButton().setVisible(True)
        c.view.getOccupatoLabel().setVisible(False)
        if isinstance(c.model.lavoro, OperatoreAlPubblico) and \
                c.model.lavoro.isOccupato(c.parent.previous.model.data_inizio, c.parent.previous.model.data_fine):
            if c.parent.previous.model not in c.model.lavoro.turni:
                c.view.getOccupatoLabel().setVisible(True)
            c.view.getSelezionaButton().setEnabled(False)
            c.view.getSelezionaButton().setStyleSheet(open(UI_DIR + '/css/grayButton.css', 'r').read())
