#######################################################
# 
# CloudStorage.py
# Python implementation of the Interface CloudStorage
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################


class CloudStorage:
    def download(cloudPath : str, localPath : str) -> None:
        pass

    def upload(localPath : str, cloudPath : str) -> None:
        pass

    def listFile(cloudDirectory : str) -> None:
        pass