#######################################################
# 
# CloudStorage.py
# Python implementation of the Interface CloudStorage
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
import abc


class CloudStorage(abc.ABC):
    @abc.abstractmethod
    def download(self, cloudPath: str, localPath: str) -> None:
        pass

    @abc.abstractmethod
    def upload(self, path: str, filename: str) -> None:
        pass

    @abc.abstractmethod
    def listFile(self, cloudDirectory: str) -> None:
        pass
