#######################################################
# 
# DropBoxAPI.py
# Python implementation of the Class DropBoxAPI
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import CloudStorage

class DropBoxAPI(CloudStorage):
    def download(cloudPath : str, localPath : str) -> None:
        pass

    def upload(localPath : str, cloudPath : str) -> None:
        pass

    def listFile(cloudDirectory : str) -> None:
        pass

    def __init__(self,):
        pass