#######################################################
# 
# EmailMessage.py
# Python implementation of the Class EmailMessage
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import Notification

class EmailMessage(Notification):
    def send(title : str, content : str) -> None:
        pass

    def create(email : str):
        pass

    def getEmail(self) -> str:
        pass