#######################################################
# 
# EmailMessage.py
# Python implementation of the Class EmailMessage
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################

from backend.low_level.network.notification import Notification


class EmailMessage(Notification):
    def __init__(self, email: str):
        self.email = email

    def send(self, title: str, content: str) -> None:
        # Gmail Account for Development necessario
        pass
