#######################################################
# 
# Notification.py
# Python implementation of the Interface Notification
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################


class Notification:
    def send(title : str, content : str) -> None:
        pass