#######################################################
# 
# SMSMessage.py
# Python implementation of the Class SMSMessage
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import Notification

class SMSMessage(Notification):
    def send(title : str, content : str) -> None:
        pass

    def create(telefono : int):
        pass

    def getTelefono(self) -> int:
        pass