#######################################################
# 
# GraficoSuSesso.py
# Python implementation of the Class GraficoSuSesso
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import Grafico
from frontend.controller.controller import ControllerVistaStatistiche

class GraficoSuSesso(Grafico):
    def create(controller : ControllerVistaStatistiche, statistica : Grafico):
        pass

    def calcola(self) -> None:
        pass