#######################################################
# 
# Grafico.py
# Python implementation of the Class Grafico
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.amministrazione.decorator_statistica.statistica import Statistica


class Grafico(Statistica):
    def __init__(self, controller: 'ControllerVistaStatistiche', statistica: 'Statistica'):
        self.controller = controller
        self.statistica = statistica

    def calcola(self) -> None:
        pass
