#######################################################
# 
# GraficoSuProvenienza.py
# Python implementation of the Class GraficoSuProvenienza
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import Grafico
from frontend.controller.controller import ControllerVistaStatistiche

class GraficoSuProvenienza(Grafico):
    def __init__(self,controller : ControllerVistaStatistiche, statistica : Grafico):
        pass

    def calcola(self) -> None:
        pass