#######################################################
# 
# Grafico.py
# Python implementation of the Class Grafico
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.amministrazione.decorator_statistica.statistica import Statistica

import abc


class Grafico( Statistica, metaclass=abc.ABCMeta):
    def __init__(self, controller: 'ControllerVistaStatistiche', wrappee: Statistica):
        self.controller = controller
        self.wrappee = wrappee

    def calcola(self) -> None:
        self.wrappee.calcola()
