#######################################################
# 
# Statistica.py
# Python implementation of the Interface Statistica
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################

import abc


class Statistica(abc.ABC):

    @abc.abstractmethod
    def calcola(self) -> None:
        pass
