#######################################################
# 
# StrategyConvalidaBiglietto.py
# Python implementation of the Class StrategyConvalidaBiglietto
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import ControllerConvalida
import StrategyConvalida

class StrategyConvalidaBiglietto(StrategyConvalida):
    def initializeUi(c : ControllerConvalida) -> None:
        pass

    def finalizza(c : ControllerConvalida) -> None:
        pass

    def initializeUi(c : ControllerConvalida) -> None:
        pass

class StrategyConvalidaBiglietto(StrategyConvalida):
    def initializeUi(c : ControllerConvalida) -> None:
        pass

    def finalizza(c : ControllerConvalida) -> None:
        pass

    def initializeUi(c : ControllerConvalida) -> None:
        pass