#######################################################
#
# StrategyConvalida.py
# Python implementation of the Interface StrategyConvalida
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
#
#######################################################

import abc


class StrategyConvalida(abc.ABC):
    @abc.abstractmethod
    def initializeUi(self, c: 'ControllerConvalida') -> None:
        pass

    @abc.abstractmethod
    def finalizza(self, c: 'ControllerConvalida', id: str) -> bool:
        pass
