#######################################################
# 
# StrategyRicercaAbbonamento.py
# Python implementation of the Class StrategyRicercaAbbonamento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.segreteria.strategy_convalida.strategy_convalida import StrategyConvalida


class StrategyRicercaAbbonamento(StrategyConvalida):
    def initializeUi(c : 'ControllerConvalida') -> None:
        pass

    def finalizza(c : 'ControllerConvalida') -> None:
        pass
