#######################################################
# 
# StrategyConvalida.py
# Python implementation of the Interface StrategyConvalida
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################


class StrategyConvalida:
    def initializeUi(c : 'ControllerConvalida') -> None:
        pass

    def finalizza(c: 'ControllerConvalida') -> None:
        pass