#######################################################
# 
# Abbonamento.py
# Python implementation of the Class Abbonamento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
import TipoAbbonamento
import datetime
import Documento

class Abbonamento(Documento):
    m_TipoAbbonamento= TipoAbbonamento()

    def create(dataRilascio : datetimetime = None, tipo : TipoAbbonamento):
        pass

    def isScaduto(self) -> bool:
        pass

    def giorniAllaScadenza(self) -> int:
        pass

    def getTipo(self) -> TipoAbbonamento:
        pass

    def convalida(self) -> bool:
        pass

    def getDataUltimoRinnovo(self) -> datetime:
        pass

    def rinnova(tipo : TipoAbbonamento) -> float:
        pass