#######################################################
# 
# Abbonamento.py
# Python implementation of the Class Abbonamento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
from datetime import datetime

from backend.high_level.clientela.documento import Documento
from backend.high_level.clientela.enum.tipo_abbonamento import TipoAbbonamento
from backend.low_level.pagamenti.nexi_api import NexiApi


class Abbonamento(Documento):

    def __init__(self, tipo: TipoAbbonamento, dataRilascio: datetime = None):
        super().__init__(NexiApi(), dataRilascio)
        self.data_ultimo_rinnovo = dataRilascio
        self.tipo = tipo

    def calcolaCosto(self) -> float:
        return self.tipo.cost

    def convalida(self) -> bool:
        self.date_convalida.append(datetime.now())
        return self.pagato and not self.isScaduto()

    def isScaduto(self) -> bool:
        return self.giorniAllaScadenza() > 0

    def giorniAllaScadenza(self) -> int:
        return self.tipo.days - (datetime.now() - self.data_ultimo_rinnovo).days

    def rinnova(self, tipo: TipoAbbonamento) -> None:
        self.tipo = tipo
        self.acquista()
