#######################################################
# 
# Cliente.py
# Python implementation of the Class Cliente
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
import datetime

from backend.high_level.clientela.enum.sesso import Sesso
from backend.high_level.clientela.visitatore import Visitatore


class Cliente(Visitatore):
    def __init__(self, nome: str, cognome: str, codFis: str, prov: str = "", sesso: Sesso = Sesso.NON_SPECIFICATO,
                 nasc: datetime.datetime = None, email: str = "", tel: str = ''):
        super().__init__(prov, sesso, nasc)
        self.nome=nome
        self.cognome=cognome
        self.codice_fiscale=codFis
        self.email=email
        self.telefono=tel
        self.abbonamenti=[]
        self.data_registrazione=datetime.datetime.now()