#######################################################
# 
# Documento.py
# Python implementation of the Class Documento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import Pagamento
import QRCode
import Subscriber
import Convalidabile

class Documento(Convalidabile):
    m_QRCode= QRCode()

    m_Subscriber= Subscriber()

    def calcolaCosto(self) -> float:
        pass

    def convalida(self) -> bool:
        pass

    def stampa(self) -> Canvas:
        pass

    def generaQRCode(self) -> QRCode:
        pass

    def acquista(self) -> bool:
        pass

    def __init__(self,dataRilascio : datetimetime = None):
        pass

    def getDataRilascio(self) -> datetimetime:
        pass

    def getDataConvalida(self) -> datetimetime:
        pass

    def getQRCode(self) -> QRCode:
        pass

    def subscribe(s : Subscriber) -> None:
        pass

    def unsubscribe(s : Subscriber) -> None:
        pass

    def notify(self) -> None:
        pass