#######################################################
# 
# QRCode.py
# Python implementation of the Class QRCode
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import Encoding

class QRCode:
    def __genara(self) -> None:
        pass

    def rigenera(self) -> None:
        pass

    def __init__(self,):
        pass

    def getId(self) -> str:
        pass

    def getImage(self) -> PilImage:
        pass