#######################################################
# 
# QRCode.py
# Python implementation of the Class QRCode
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import random
import string

from backend.low_level.sicurezza.encoding import Encoding


class QRCode:
    def __init__(self, encoding: Encoding):
        self.id = self.__genara()
        self.encoding = encoding

    def __genara(self) -> str:
        return ''.join(random.choice(string.ascii_uppercase) for _ in range(10))

    def rigenera(self) -> None:
        self.id = self.__genara()

    def getImage(self) -> None:
        return self.encoding.encode(self.id)
