#######################################################
# 
# Subscriber.py
# Python implementation of the Interface Subscriber
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################


class Subscriber:
    def updatetime(self) -> None:
        pass