#######################################################
# 
# Visitatore.py
# Python implementation of the Class Visitatore
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
import Sesso
import Biglietto

class Visitatore:
    m_Biglietto= Biglietto()

    m_Sesso= Sesso()

    def __init__(self,prov : str = "", sesso : Sesso = Sesso.NonSpecificato, nasc : datetime = None):
        pass

    def getProvenienza(self) -> str:
        pass

    def setProvenienza(newVal : str) -> None:
        pass

    def getSesso(self) -> Sesso:
        pass

    def setSesso(newVal : Sesso) -> None:
        pass

    def getDataNascita(self) -> datetimetime:
        pass

    def setDataNascita(newVal : datetimetime) -> None:
        pass

    def getListaBiglietti(self) -> Biglietto:
        pass