#######################################################
# 
# Visitatore.py
# Python implementation of the Class Visitatore
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from datetime import datetime

from backend.high_level.clientela.biglietto import Biglietto
from backend.high_level.clientela.enum.sesso import Sesso


class Visitatore:

    def __init__(self, provenienza: str = "", sesso: Sesso = Sesso.NON_SPECIFICATO,
                 dataNascita: datetime = None, biglietti: list[Biglietto] = None):
        self.provenienza = provenienza
        self.sesso = sesso
        self.data_nascita = dataNascita
        self.biglietti: list[Biglietto] = biglietti if biglietti is not None else []
        self.data_inserimento = datetime.now()

    def calcolaEta(self) -> int:
        return datetime.today().year - self.data_nascita.year - \
               ((datetime.today().month, datetime.today().day) < (self.data_nascita.month, self.data_nascita.day))
