#######################################################
# 
# WidgetTurnoGuida.py
# Python implementation of the Class WidgetTurnoGuida
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
import QWidget

class WidgetTurnoGuida(QWidget):
    def getIcon(self) -> QLabel:
        pass

    def getNomeLabel(self) -> QLabel:
        pass

    def getOrarioLabel(self) -> QLabel:
        pass

    def getPostiDisponibiliLabel(self) -> QLabel:
        pass

    def getSelezionaButton(self) -> QPushButton:
        pass

    def getRimuoviButton(self) -> QPushButton:
        pass

    def getModificaButton(self) -> QPushButton:
        pass