#######################################################
# 
# WidgetTurnoGuida.py
# Python implementation of the Class WidgetTurnoGuida
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QLabel, QPushButton, QWidget

from frontend.ui.location import UI_DIR
from frontend.view.my_widget import MyWidget


class WidgetTurnoGuida(MyWidget):

    def __init__(self,  parent):
        super().__init__(UI_DIR + '/GestisciTurnoGuidaWidget.ui', parent)

    def getIcon(self) -> QLabel:
        return self.iconLabel

    def getNomeLabel(self) -> QLabel:
        return self.nomeLabel

    def getOrarioLabel(self) -> QLabel:
        return self.orarioLabel

    def getPostiDisponibiliLabel(self) -> QLabel:
        return self.postiLiberiLabel

    def getSelezionaButton(self) -> QPushButton:
        return self.selezionaButton

    def getRimuoviButton(self) -> QPushButton:
        return self.rimuoviButton

    def getModificaButton(self) -> QPushButton:
        return self.modificaButton
