#######################################################
#
# WidgetTurnoGuida.py
# Python implementation of the Class WidgetOpera
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
#
#######################################################
from PyQt5.QtWidgets import QLabel, QPushButton, QWidget

from frontend.ui.location import UI_DIR
from frontend.view.my_widget import MyWidget


class WidgetOpera(MyWidget):

    def __init__(self, parent):
        super().__init__(UI_DIR + '/operaWidget.ui', parent)

    def getOperaLabel(self) -> QLabel:
        return self.operaLabel