#######################################################
# 
# PeriodoStorico.py
# Python implementation of the Enumeration PeriodoStorico
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################


class PeriodoStorico:
    pass