#######################################################
# 
# ControllerWidgetRichiestaDonazione.py
# Python implementation of the Class ControllerWidgetRichiestaDonazione
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import RichiestaDonazione
import WidgetRichiestaDonazione
from frontend.controller.controller import Controller

class ControllerWidgetRichiestaDonazione(Controller):
    m_WidgetRichiestaDonazione= WidgetRichiestaDonazione()

    def __gotoVistaOpera(self) -> None:
        pass

    def create(view : WidgetRichiestaDonazione, model : RichiestaDonazione):
        pass

    def __onRifiutaClicked(self) -> None:
        pass

    def __onAccettaClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass