#######################################################
# 
# Pagamento.py
# Python implementation of the Interface Pagamento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import abc
import random


class Pagamento(abc.ABC):
    @abc.abstractmethod
    def paga(self, costo: float) -> bool:
        # simulazione embedded
        return random.choices([True, False],[3,1])
