#######################################################
# 
# ControllerMostra.py
# Python implementation of the Class ControllerMostra
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import Mostra
from frontend.controller.controller import Controller
from frontend.view import VistaMostra

class ControllerMostra(Controller):
    m_VistaMostra= VistaMostra()

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self, view: VistaMostra, previous: Controller, model: Mostra):
        super().__init__(view)
        self.view: VistaMostra = view
        self.previous = previous
        self.model = model
        self.initializeUi()
        self.connettiEventi()

    def __gotoVistaOpera(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass