#######################################################
# 
# ControllerAcquistoOpere.py
# Python implementation of the Class ControllerAcquistoOpere
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
import Museo
from frontend.controller.controller import Controller
from frontend.view import VistaAcquistoOpere

class ControllerAcquistoOpere(Controller):
    m_VistaAcquistoOpere= VistaAcquistoOpere()

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self,view : VistaGestioneMostre, previous : Controller, model : Museo):
        pass

    def __gotoVistaAggiungiOpera(self) -> None:
        pass

    def __gotoVistaRicercaOpera(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass