#######################################################
# 
# ControllerBackups.py
# Python implementation of the Class ControllerBackups
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
import Museo
from frontend.controller.controller import Controller
from frontend.view import VistaBackups
from frontend.controller.controller import ControllerBackup

class ControllerBackups(Controller):
    m_VistaBackups= VistaBackups()

    m_ControllerBackup= ControllerBackup()

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self,view : VistaBackups, previous : Controller, model : Museo):
        pass

    def __onBackupOraClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def initializeUi(self) -> None:
        pass

    def __renderizzaBackups(self) -> ControllerWidgetBackup []:
        pass