#######################################################
# 
# ControllerVistaStatistiche.py
# Python implementation of the Class ControllerVistaStatistiche
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtChart import QChartView

from frontend.controller.controller import Controller
from frontend.view.amministrazione.vista_statistiche import VistaStatistiche


class ControllerVistaStatistiche(Controller):

    def __gotoPrevious(self) -> None:
        self.closeView()
        self.previous.initializeUi()
        self.previous.enableView()

    def __init__(self, view: VistaStatistiche, previous: Controller):
        super().__init__(view)
        self.view: VistaStatistiche = view
        self.previous = previous
        self.connettiEventi()

    def __onVisualizzaClicked(self) -> None:
        pass #TODO

    def __onLeftArrowClicked(self) -> None:
        pass #TODO

    def __onRightArrowClicked(self) -> None:
        pass #TODO

    def connettiEventi(self) -> None:
        self.view.getPreviousButton().mouseReleaseEvent = lambda _: self.__gotoPrevious()
        self.view.getVisualizzaButton().clicked.connect(self.__onVisualizzaClicked())
        self.view.getLeftArrowIcon().mouseReleaseEvent = lambda _: self.__onLeftArrowClicked()
        self.view.getRightArrowIcon().mouseReleaseEvent = lambda _: self.__onRightArrowClicked()

    def addGrafico(chart : QChartView) -> None:
        pass #TODO

    def mostraStatistiche(clientiTotali : int, mediaGiornaliera : float, devStdGiornaliera : float) -> None:
        pass #TODO