#######################################################
# 
# ControllerVistaReportIncassi.py
# Python implementation of the Class ControllerVistaReportIncassi
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import datetime

from backend.high_level.museo import Museo
from frontend.controller.controller import Controller
from frontend.view.amministrazione.vista_report_incassi import VistaReportIncassi


class ControllerVistaReportIncassi(Controller):

    def __gotoPrevious(self) -> None:
        self.closeView()
        self.previous.initializeUi()
        self.previous.enableView()

    def __init__(self, view: VistaReportIncassi, previous: Controller, model: Museo):
        super().__init__(view)
        self.view: VistaReportIncassi = view
        self.previous = previous
        self.model = model
        self.initializeUi()
        self.connettiEventi()

    def __onVisualizzaClicked(self) -> None:
        pass #TODO

    def connettiEventi(self) -> None:
        self.view.getPreviousButton().mouseReleaseEvent = lambda _: self.__gotoPrevious()
        self.view.getVisualizzaButton().clicked.connect(self.__onVisualizzaClicked())

    def __generaGrafico(self) -> None:
        pass #TODO

    def initializeUi(self) -> None:
        self.view.getAcquistoOpereLabel().setText()
        self.view.getVenditaOpereLabel().setText()
        self.view.getAbbonamentiLabel().setText()
        self.view.getBigliettiLabel().setText()
        self.view.getMeseLineEdit().setText(datetime.datetime.today().strftime("%m/%Y"))
        #TODO controllare riga sopra
        pass #TODO settare tutti i testi