#######################################################
# 
# ControllerGestionePostiLavoro.py
# Python implementation of the Class ControllerGestionePostiLavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
from backend.high_level.museo import Museo
from frontend.controller.amministrazione.widget.controller_widget_posto_lavoro import ControllerWidgetPostoLavoro
from frontend.controller.controller import Controller
from frontend.view.amministrazione.vista_gestione_posti_lavoro import VistaGestionePostiLavoro


class ControllerGestionePostiLavoro(Controller):

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self, view: VistaGestionePostiLavoro, previous: Controller, model: Museo):
        super().__init__(view)

    def gotoVistaModificaPostoLavoro(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def __renderizzaPostiLavoro(self) -> list[ControllerWidgetPostoLavoro]:
        pass

    def initializeUi(self) -> None:
        self.posti_lavoro = self.__renderizzaPostiLavoro()
        matches={
            Reception:self.verticalLayout,
            Segreteria:self.verticalLayout_2,
            Amministrazione:self.verticalLayout_3,
        }
        for controller in self.posti_lavoro:
            matches[type(controller.model)].addWidget(controller.view.widget)
