#######################################################
# 
# ControllerModificaPostoLavoro.py
# Python implementation of the Class ControllerModificaPostoLavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import PostoLavoro
from frontend.controller.controller import Controller
from frontend.view import VistaModificaPostoLavoro

class ControllerModificaPostoLavoro(Controller):
    m_VistaModificaPostoLavoro= VistaModificaPostoLavoro()

    def __gotoPrevious(self) -> None:
        pass

    def create(view : VistaModificaPostoLavoro, previous : Controller, model : PostoLavoro):
        pass

    def __onConfermaClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def initializeUi(self) -> None:
        pass