#######################################################
# 
# ControllerVistaStatistiche.py
# Python implementation of the Class ControllerVistaStatistiche
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import Controller
from frontend.view import VistaStatistiche
import Statistica

class ControllerVistaStatistiche(Controller):
    m_VistaStatistiche= VistaStatistiche()

    m_Statistica= Statistica()

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self,view : VistaStatistiche, previous : Controller):
        pass

    def __onVisualizzaClicked(self) -> None:
        pass

    def __onLeftArrowClicked(self) -> None:
        pass

    def __onRightArrowClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def addGrafico(chart : QChartView) -> None:
        pass

    def mostraStatistiche(clientiTotali : int, mediaGiornaliera : float, devStdGiornaliera : float) -> None:
        pass