#######################################################
# 
# ControllerModificaTurnoGuida.py
# Python implementation of the Class ControllerModificaTurnoGuida
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import TurnoGuida
from frontend.controller.controller import Controller
from frontend.view import VistaModificaTurnoGuida

class ControllerModificaTurnoGuida(Controller):
    m_VistaModificaTurnoGuida= VistaModificaTurnoGuida()

    def __gotoPrevious(self) -> None:
        pass

    def create(view : VistaModificaTurnoGuida, previous : Controller, model : TurnoGuida):
        pass

    def __gotoGestisciDipendenti(self) -> None:
        pass

    def __onConfermaClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass