#######################################################
# 
# ControllerBackups.py
# Python implementation of the Class ControllerBackups
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
from backend.high_level.museo import Museo
from frontend.controller.amministrazione.widget.controller_widget_backup import  ControllerWidgetBackup
from frontend.controller.controller import Controller
from frontend.view.amministrazione.vista_backups import VistaBackups


class ControllerBackups(Controller):

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self,view : VistaBackups, previous : Controller, model : Museo):
        pass

    def __onBackupOraClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def initializeUi(self) -> None:
        pass

    def __renderizzaBackups(self) -> list[ControllerWidgetBackup]:
        pass