#######################################################
# 
# ControllerVistaReportIncassi.py
# Python implementation of the Class ControllerVistaReportIncassi
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import Controller
import Museo
from frontend.view import VistaReportIncassi

class ControllerVistaReportIncassi(Controller):
    m_VistaReportIncassi= VistaReportIncassi()

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self,view : VistaReportIncassi, previous : Controller, model : Museo):
        pass

    def __onVisualizzaClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def __generaGrafico(self) -> None:
        pass