#######################################################
# 
# ControllerModificaPostoLavoro.py
# Python implementation of the Class ControllerModificaPostoLavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
from backend.high_level.personale.posto_lavoro import PostoLavoro
from frontend.controller.controller import Controller
from frontend.view.amministrazione.vista_modifica_posto_lavoro import VistaModificaPostoLavoro


class ControllerModificaPostoLavoro(Controller):

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self, view: VistaModificaPostoLavoro, previous: Controller, model: PostoLavoro):
        super().__init__(view)

    def __onConfermaClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def initializeUi(self) -> None:
        pass