#######################################################
# 
# ControllerVistaReportIncassi.py
# Python implementation of the Class ControllerVistaReportIncassi
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
from backend.high_level.museo import Museo
from frontend.controller.controller import Controller
from frontend.view.amministrazione.vista_report_incassi import VistaReportIncassi


class ControllerVistaReportIncassi(Controller):

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self, view: VistaReportIncassi, previous: Controller, model: Museo):
        super().__init__(view)

    def __onVisualizzaClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def __generaGrafico(self) -> None:
        pass