#######################################################
# 
# ControllerAccount.py
# Python implementation of the Class ControllerAccount
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
import Dipendente
from frontend.controller.controller import Controller
from frontend.view import VistaAccount

class ControllerAccount(Controller):
    m_VistaAccount= VistaAccount()

    def __gotoPrevious(self) -> None:
        pass

    def __gotoHome(self) -> None:
        pass

    def __init__(self,view : VistaAccount, previous : Controller, home : Controller, dipendente : Dipendente):
        pass

    def connettiEventi(self) -> None:
        pass

    def initializeUi(self) -> None:
        pass