#######################################################
# 
# ControllerAccount.py
# Python implementation of the Class ControllerAccount
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
from backend.high_level.personale.dipendente import Dipendente
from frontend.controller.controller import Controller
from frontend.view.vista_account import VistaAccount


class ControllerAccount(Controller):

    def __gotoPrevious(self) -> None:
        pass

    def __gotoHome(self) -> None:
        pass

    def __init__(self, view: VistaAccount, previous: Controller, home: Controller, dipendente: Dipendente):
        super().__init__(view)
        self.view: VistaAccount = view
        self.previous=previous
        self.home = home
        self.dipendente = dipendente


    def connettiEventi(self) -> None:
        pass

    def initializeUi(self) -> None:
        pass