#######################################################
# 
# Controller.py
# Python implementation of the Class Controller
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel
from frontend.view.my_main_window import MyMainWindow
from ui.location import ROOT_DIR

class Controller:
    def initializeUi(self) -> None:
        pass

    def showView(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def create(view : QMainWindow):
        pass