#######################################################
# 
# ControllerLogin.py
# Python implementation of the Class ControllerLogin
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
# from backend.high_level.museo import Museo
# from backend.high_level.personale.dipendente import Dipendente
from backend.low_level.sicurezza.hashing import Hashing
from frontend.controller.controller import Controller
from frontend.view.vista_login import VistaLogin


class ControllerLogin(Controller):
    def __login(self,username : str, passwordEncr : str) -> None:
        pass

    def __onLoginClicked(self) -> None:
        dipendente=self.__login(
            self.view.getUsernameLineEdit().text,
            self.__hashing.hash(self.view.getPasswordLineEdit().text)
        )

    def connettiEventi(self) -> None:
        self.view.getPreviousLabel().mousePressEvent =lambda _: self.gotoHome()
        self.view.getLoginButton().clicked.connect(self.__onLoginClicked)

    def gotoHome(self) -> None:
        self.closeView()
        self.__home.enableView()

    def __init__(self, view: VistaLogin, model: None, home: Controller, repartoScelto: str,hashing:Hashing):
        super().__init__(view)
        self.__model=model
        self.__home=home
        self.__repartoScelto=repartoScelto
        self.__hashing=hashing
