#######################################################
# 
# Museo.py
# Python implementation of the Class Museo
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import datetime

from backend.high_level.clientela.enum.sesso import Sesso
from backend.high_level.clientela.visitatore import Visitatore
from backend.high_level.gestione_interna.enum.reparto_museo import RepartoMuseo
from backend.high_level.gestione_interna.mostra import Mostra
from backend.high_level.gestione_interna.opera import Opera
from backend.high_level.gestione_interna.turno_guida import TurnoGuida
from backend.high_level.personale.dipendente import Dipendente
from backend.high_level.personale.operatore_al_pubblico import OperatoreAlPubblico
from backend.high_level.personale.posto_lavoro import PostoLavoro
from backend.low_level.io.serializzatore import Serializzatore
from backend.low_level.network.cloud_storage import CloudStorage


class Museo():
    m_Dipendente = Dipendente()

    m_Visitatore = Visitatore()

    m_Mostra = Mostra()

    m_TurnoGuida = TurnoGuida()

    m_PostoLavoro = PostoLavoro()

    m_Opera = Opera()

    @staticmethod
    def getInstance() -> Museo:
        return None

    def getTurniGuide(self) -> list:
        pass

    def getGuide(self) -> list:
        pass

    def getPostiLavoro(self) -> list:
        pass

    def login(username: str, password: str) -> Dipendente:
        pass

    def getDipendenti(self) -> list:
        pass

    def getName(self) -> str:
        pass

    def getSitoWeb(self) -> str:
        pass

    def rimuoviTurno(guida: OperatoreAlPubblico, turno: TurnoGuida) -> bool:
        pass

    def __create(self) -> None:
        pass

    def setSitoWeb(newVal: str) -> None:
        pass

    def getDataFondazione(self) -> datetime.datetime:
        pass

    def getIndirizzo(self) -> str:
        pass

    def getTelefonoFisso(self) -> int:
        pass

    def setTelefonoFisso(newVal: int) -> None:
        pass

    def getEmail(self) -> str:
        pass

    def setEmail(newVal: str) -> None:
        pass

    def setDescrizione(newVal: str) -> None:
        pass

    def getDescrizione(self) -> str:
        pass

    def backup(self) -> None:
        pass

    def getSerializzatore(self) -> Serializzatore:
        pass

    def setSerializzatore(newVal: Serializzatore) -> None:
        pass

    def getCloudStorage(self) -> CloudStorage:
        pass

    def setCloudStorage(newVal: CloudStorage) -> None:
        pass

    def initializeInstance(nome: str, sitoWeb: str, dataFondazione: datetime, indirizzo: str, telefonoFisso: int,
                           email: str, descrizione: str) -> None:
        pass

    def aggiungiTurno(guida: OperatoreAlPubblico, reparto: RepartoMuseo, dataInizio: datetime.datetime,
                      dataFine: datetime.datetime) -> None:
        pass

    def aggiungiDipendente(nome: str, cognome: str, dataNascita: datetime.datetime, sesso: Sesso = Sesso.nonSpecificato,
                           curriculum: str = None) -> None:
        pass

    def rimuoviDipendente(dipendente: Dipendente) -> bool:
        pass
