#######################################################
# 
# StrategyRiceviDonazione.py
# Python implementation of the Class StrategyRiceviDonazione
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import ControllerAggiungiOpera
import StrategyAggiungiOpera

class StrategyRiceviDonazione(StrategyAggiungiOpera):
    def initializeUi(c : ControllerAggiungiOpera) -> None:
        pass

    def onConfermaClicked(c : ControllerAggiungiOpera) -> None:
        pass

    def initializeUi(c : ControllerAggiungiOpera) -> None:
        pass

    def onConfermaClicked(c : ControllerAggiungiOpera) -> None:
        pass