#######################################################
# 
# StrategyAggiungiOpera.py
# Python implementation of the Interface StrategyAggiungiOpera
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.reception.controller_aggiungi_opera import ControllerAggiungiOpera


class StrategyAggiungiOpera:
    def initializeUi(c : ControllerAggiungiOpera) -> None:
        pass

    def onConfermaClicked(c : ControllerAggiungiOpera) -> None:
        pass