#######################################################
# 
# StrategyRiceviDonazione.py
# Python implementation of the Class StrategyRiceviDonazione
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.reception.strategy_aggiungi_opera.strategy_aggiungi_opera import StrategyAggiungiOpera


class StrategyRiceviDonazione(StrategyAggiungiOpera):
    def initializeUi(self, c: 'ControllerAggiungiOpera') -> None:
        pass

    def onConfermaClicked(self, c: 'ControllerAggiungiOpera') -> None:
        pass
