#######################################################
# 
# StrategyAggiungiOpera.py
# Python implementation of the Interface StrategyAggiungiOpera
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################

import abc
class StrategyAggiungiOpera(abc.ABC):
    @abc.abstractmethod
    def initializeUi(c : 'ControllerAggiungiOpera') -> None:
        pass

    @abc.abstractmethod
    def onConfermaClicked(c : 'ControllerAggiungiOpera') -> None:
        pass