#######################################################
# 
# AggiungiTurnoGuida.py
# Python implementation of the Class AggiungiTurnoGuida
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import ControllerTurniGuide
import StrategyAggiungiAllaLista

class AggiungiTurnoGuida(StrategyAggiungiAllaLista):
    def onClicked(self) -> None:
        pass

    def __init__(self,c : ControllerTurniGuide):
        pass

    def getIcon(self) -> QIcon:
        pass