#######################################################
# 
# AggiungiOpera.py
# Python implementation of the Class AggiungiOpera
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtGui import QPixmap

from frontend.controller.amministrazione.widget.strategy_aggiungi_alla_lista.strategy_aggiungi_alla_lista import \
    StrategyAggiungiAllaLista


class AggiungiOpera(StrategyAggiungiAllaLista):
    def __init__(self):
        self.controller: 'ControllerWidgetAggiungiAllaLista' = None

    def onClicked(self) -> None:
        pass

    def getIcon(self) -> QPixmap:
        return QPixmap(":/icons/add_photo_alternate_FILL1_wght600_GRAD200_opsz48_risultato.png")
