#######################################################
# 
# AggiungiPostoLavoro.py
# Python implementation of the Class AggiungiPostoLavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import ControllerGestionePostiLavoro
import StrategyAggiungiAllaLista

class AggiungiPostoLavoro(StrategyAggiungiAllaLista):
    def onClicked(self) -> None:
        pass

    def create(c : ControllerGestionePostiLavoro):
        pass

    def getIcon(self) -> QIcon:
        pass