#######################################################
# 
# AggiungiOpera.py
# Python implementation of the Class AggiungiOpera
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import ControllerAllestisciMostra
import StrategyAggiungiAllaLista

class AggiungiOpera(StrategyAggiungiAllaLista):
    def onClicked(self) -> None:
        pass

    def create(c : ControllerAllestisciMostra):
        pass

    def getIcon(self) -> QIcon:
        pass