#######################################################
# 
# AggiungiPostoLavoro.py
# Python implementation of the Class AggiungiPostoLavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtGui import QPixmap

from backend.high_level.museo import Museo
from backend.high_level.personale.amministrazione import Amministrazione
from backend.high_level.personale.reception import Reception
from backend.high_level.personale.segreteria import Segreteria

import frontend.controller.amministrazione.controller_modifica_posto_lavoro as controller_modifica_posto_lavoro
from frontend.ui.location import UI_DIR
from frontend.view.amministrazione.vista_modifica_posto_lavoro import VistaModificaPostoLavoro

from frontend.controller.amministrazione.widget.strategy_aggiungi_alla_lista.strategy_aggiungi_alla_lista import \
    StrategyAggiungiAllaLista


class AggiungiPostoLavoro(StrategyAggiungiAllaLista):

    def __init__(self):
        self.controller:'ControllerWidgetAggiungiAllaLista' = None

    def onClicked(self) -> None:
        matches = {
            'reception': Reception('', 0, 0, 1),
            'segreteria': Segreteria('', 0, 0, 1, ''),
            'amministrazione': Amministrazione('', 0, 0)
        }
        Museo.getInstance().posti_lavoro.append(matches[self.controller.tipo])
        controller = controller_modifica_posto_lavoro.ControllerModificaPostoLavoro(
            view=VistaModificaPostoLavoro(),
            previous=self.controller.parent,
            model=matches[self.controller.tipo],
        )
        controller.showView()
        self.controller.parent.disableView()

    def getIcon(self) -> QPixmap:
        return QPixmap(":/icons/add_business_FILL1_wght600_GRAD200_opsz48_risultato.png")

    def initializeUi(self) -> None:
        self.controller.view.aggiungiAllaListaWidget.setStyleSheet(
            open(UI_DIR + '/css/dottedBorderThick.css', 'r').read())
