#######################################################
# 
# StrategyVendiOpera.py
# Python implementation of the Class StrategyVendiOpera
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import ControllerRicercaOpera
import StrategyRicercaOpera

class StrategyVendiOpera(StrategyRicercaOpera):
    def initializeUi(c : ControllerRicercaOpera) -> None:
        pass

    def onOperaClicked(c : ControllerRicercaOpera) -> None:
        pass

    def initializeUi(c : ControllerRicercaOpera) -> None:
        pass