#######################################################
# 
# StrategyRicercaSulWeb.py
# Python implementation of the Class StrategyRicercaSulWeb
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.reception.strategy_ricerca_opera.strategy_ricerca_opera import StrategyRicercaOpera


class StrategyRicercaSulWeb(StrategyRicercaOpera):
    def initializeUi(self, c: 'ControllerRicercaOpera') -> None:
        pass

    def onOperaClicked(self, c: 'ControllerWidgetOpera') -> None:
        pass
    def initializeWidgetUi(self, c: 'ControllerWidgetOpera'):
        pass