#######################################################
# 
# StrategyRicercaOpera.py
# Python implementation of the Interface StrategyRicercaOpera
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import ControllerRicercaOpera

class StrategyRicercaOpera:
    def initializeUi(c : ControllerRicercaOpera) -> None:
        pass

    def onOperaClicked(c : ControllerRicercaOpera) -> None:
        pass