#######################################################
# 
# StrategyRicercaOpera.py
# Python implementation of the Interface StrategyRicercaOpera
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
import abc


class StrategyRicercaOpera(abc.ABC):
    @abc.abstractmethod
    def initializeUi(self, c: 'ControllerRicercaOpera') -> None:
        pass

    @abc.abstractmethod
    def onOperaClicked(self, c: 'ControllerWidgetOpera') -> None:
        pass
