#######################################################
# 
# StrategyAggiungiOperaAMostra.py
# Python implementation of the Class StrategyAggiungiOperaAMostra
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.reception.controller_ricerca_opera import ControllerRicercaOpera
from frontend.controller.reception.strategy_ricerca_opera.strategy_ricerca_opera import StrategyRicercaOpera


class StrategyAggiungiOperaAMostra(StrategyRicercaOpera):
    def initializeUi(self,c : ControllerRicercaOpera) -> None:
        c.view.getHeaderLabel().setText('AllestisciMostra ➜ RicercaOpera')

    def onOperaClicked(self,c : 'ControllerWidgetOpera') -> None:
        # c.parent.previous --> ControllerAllestisciMostra
        c.parent.previous.model.opere.append(c.model)
        c.parent.previous.initializeUi()
        c.parent.previous.enableView()
        c.parent.closeView()

