#######################################################
# 
# StrategyAggiungiOperaAMostra.py
# Python implementation of the Class StrategyAggiungiOperaAMostra
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import ControllerRicercaOpera
import StrategyRicercaOpera

class StrategyAggiungiOperaAMostra(StrategyRicercaOpera):
    def initializeUi(c : ControllerRicercaOpera) -> None:
        pass

    def onOperaClicked(c : ControllerRicercaOpera) -> None:
        pass

    def initializeUi(c : ControllerRicercaOpera) -> None:
        pass