#######################################################
# 
# StrategyTurniGuide.py
# Python implementation of the Interface StrategyTurniGuide
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import ControllerTurniGuide
from frontend.controller.controller import ControllerWidgetTurnoGuida

class StrategyTurniGuide:
    def initializeUi(c : ControllerTurniGuide) -> None:
        pass

    def initializeWidgetUi(c : ControllerWidgetTurnoGuida) -> None:
        pass