#######################################################
# 
# StrategyRicercaTurniGuide.py
# Python implementation of the Class StrategyRicercaTurniGuide
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
import frontend.controller.reception.widget.controller_widget_turno_guida as controller
from frontend.controller.reception.strategy_turni_guide.strategy_turni_guide import StrategyTurniGuide


class StrategyRicercaTurniGuide(StrategyTurniGuide):
    def initializeUi(self,c : 'ControllerTurniGuide') -> None:
        c.view.getHeaderLabel().setText('AcquistoBiglietto ➜ CercaGuida')

    def initializeWidgetUi(self,c : controller.ControllerWidgetTurnoGuida) -> None:
        c.view.getRimuoviButton().setVisible(False)
        c.view.getModificaButton().setVisible(False)