#######################################################
# 
# Pagamento.py
# Python implementation of the Interface Pagamento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import abc


class IOFile(abc.ABC):
    @abc.abstractmethod
    def salvaFile(self, content: bytes, path: str, filename:str) -> None:
        pass

    @abc.abstractmethod
    def leggiFile(self, path: str) -> str:
        pass
