#######################################################
# 
# Pagamento.py
# Python implementation of the Interface Pagamento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################


class IOFile:
    def salvaFile(self) -> None:
        pass

    def leggiFile(self) -> str:
        pass
