#######################################################
# 
# IOTextFile.py
# Python implementation of the Class IOTextFile
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
from backend.low_level.io.io_file import IOFile


class IOTextFile(IOFile):
    def create(path: str, filename: str):
        pass

    def salvaFile(self) -> None:
        pass

    def leggiFile(self) -> str:
        pass

    def getPath(self) -> str:
        pass

    def getFilename(self) -> str:
        pass
