#######################################################
# 
# SerializzazionePickle.py
# Python implementation of the Class SerializzazionePickle
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
from backend.low_level.io.serializzatore import Serializzatore


class SerializzazionePickle(Serializzatore):

    def serializza(self,path,obj : object) -> None:
        pass

    def deserializza(self,path) -> object:
        pass
