#######################################################
# 
# SerializzazionePickle.py
# Python implementation of the Class SerializzazionePickle
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import Serializzatore

class SerializzazionePickle(Serializzatore):
    def create(path : str, filename : str):
        pass

    def serializza(obj : Object) -> None:
        pass

    def deserializza(self) -> Object:
        pass

    def getPath(self) -> str:
        pass

    def getFilename(self) -> str:
        pass