#######################################################
# 
# Hashing.py
# Python implementation of the Interface Hashing
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################


class Hashing:
    def hash(plain : str) -> str:
        pass