#######################################################
# 
# MD5Hashing.py
# Python implementation of the Class MD5Hashing
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import Hashing

class MD5Hashing(Hashing):
    def hash(plain : int) -> str:
        pass

    def __init__(self,):
        pass