#######################################################
# 
# QRCodeEncoding.py
# Python implementation of the Class QRCodeEncoding
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import Encoding

class QRCodeEncoding(Encoding):
    def encode(text : str) -> Image:
        pass

    def decode(image : Image) -> str:
        pass

    def __init__(self,):
        pass