#######################################################
# 
# QRCodeEncoding.py
# Python implementation of the Class QRCodeEncoding
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import PIL
import cv2
import qrcode

from backend.low_level.sicurezza.encoding import Encoding


class QRCodeEncoding(Encoding):
    def encode(self,text : str) ->  pilimage:
        pass

    def decode(self,image : None) -> str:
        pass



