#######################################################
# 
# SHA256Hashing.py
# Python implementation of the Class SHA256Hashing
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import Hashing

class SHA256Hashing(Hashing):
    def hash(plain : int) -> str:
        pass

    def create():
        pass