#######################################################
# 
# VistaLogin.py
# Python implementation of the Class VistaLogin
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel
from frontend.view.my_main_window import MyMainWindow
from ui.location import ROOT_DIR

class VistaLogin(MyMainWindow):
    def getUsernameLineEdit(self) -> QLineEdit:
        pass

    def getPasswordLineEdit(self) -> QLineEdit:
        pass

    def getLoginButton(self) -> QPushButton:
        pass