#######################################################
# 
# VistaHome.py
# Python implementation of the Class VistaHome
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel
from frontend.view.my_main_window import MyMainWindow
from ui.location import ROOT_DIR

class VistaHome(MyMainWindow):
    def getReceptionButton(self) -> QPushButton:
        pass

    def getSegreteriaButton(self) -> QPushButton:
        pass

    def getAmministrazioneButton(self) -> QPushButton:
        pass