#######################################################
# 
# VistaYesNo.py
# Python implementation of the Class VistaYesNo
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel
from frontend.view.my_main_window import MyMainWindow
from ui.location import ROOT_DIR

class VistaYesNo(MyMainWindow):
    def getAnNoneaButton(self) -> QPushButton:
        pass

    def getConfermaButton(self) -> QPushButton:
        pass