#######################################################
# 
# VistaAccount.py
# Python implementation of the Class VistaAccount
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel
from frontend.view.my_main_window import MyMainWindow


class VistaAccount(MyMainWindow):
    def getPreviousButton(self) -> QPushButton:
        pass

    def getNomeLabel(self) -> QLabel:
        pass

    def getDataNascitaLabel(self) -> QLabel:
        pass

    def getSessoLabel(self) -> QLabel:
        pass

    def getDataAssunzioneLabel(self) -> QLabel:
        pass

    def getEmailLabel(self) -> QLabel:
        pass

    def getOccupazioneLabel(self) -> QLabel:
        pass

    def getDataAssegnazioneLavoroLabel(self) -> QLabel:
        pass

    def getLogoutButton(self) -> QPushButton:
        pass