#######################################################
# 
# VistaYesNo.py
# Python implementation of the Class VistaYesNo
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton
from frontend.view.my_main_window import MyMainWindow


class VistaYesNo(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/Y-N Message.ui')

    def getAnnullaButton(self) -> QPushButton:
        return self.annullaButton

    def getConfermaButton(self) -> QPushButton:
        return self.confermaButton