#######################################################
# 
# VistaHome.py
# Python implementation of the Class VistaHome
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton

from frontend.ui.location import UI_DIR
from frontend.view.my_main_window import MyMainWindow


class VistaHome(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/MainPage.ui')

    def getReceptionButton(self) -> QPushButton:
        return self.receptionBigButton

    def getSegreteriaButton(self) -> QPushButton:
        return self.segreteriaBigButton

    def getAmministrazioneButton(self) -> QPushButton:
        return self.amministrazioneBigButton
