#######################################################
# 
# Sesso.py
# Python implementation of the Enumeration Sesso
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################


class Sesso:
    pass