#######################################################
# 
# Sesso.py
# Python implementation of the Enumeration Sesso
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################


from enum import Enum


class Sesso(Enum):
    MASCHIO,FEMMINA,NON_SPECIFICATO,*_= range(100)
