#######################################################
# 
# Tariffa.py
# Python implementation of the Enumeration Tariffa
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################


from enum import Enum


class Tariffa(Enum):
    INTERO = 0, 8.00
    RIDOTTO = 1, 5.00
    GRATIS = 2, 0.00

    def __new__(cls, index: int, cost: float):
        member = object.__new__(cls)
        member.index = index
        member.cost = cost
        return member
