#######################################################
# 
# Tariffa.py
# Python implementation of the Enumeration Tariffa
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################


class Tariffa:
    pass