#######################################################
# 
# Tariffa.py
# Python implementation of the Enumeration Tariffa
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################


from enum import Enum


class Tariffa(Enum):
    INTERO=8.00
    RIDOTTO=5.00
    GRATIS=0.00
    def __new__(cls,  cost:float):
        member = object.__new__(cls)
        member.cost = cost
        return member