#######################################################
# 
# TipoAbbonamento.py
# Python implementation of the Enumeration TipoAbbonamento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################


class TipoAbbonamento:
    pass