#######################################################
# 
# TipoAbbonamento.py
# Python implementation of the Enumeration TipoAbbonamento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################


from enum import Enum


class TipoAbbonamento(Enum):
    MENSILE=30,9.99
    TRIMESTRALE=90,24.99
    SEMESTRALE=180,49.99
    ANNUALE=365,99.99

    def __new__(cls, days:int, cost:float):
        member = object.__new__(cls)
        member.days = days
        member.cost = cost
        return member