#######################################################
# 
# ControllerAcquistoBiglietto.py
# Python implementation of the Class ControllerAcquistoBiglietto
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
from backend.high_level.clientela.biglietto import Biglietto
from frontend.controller.controller import Controller
from frontend.view.reception.vista_acquisto_biglietto import VistaAcquistoBiglietto


class ControllerAcquistoBiglietto(Controller, Subscriber):

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self, view: VistaAcquistoBiglietto, previous: Controller, model: Biglietto):
        super().__init__(view)

    def __gotoVistaTurniGuide(self) -> None:
        pass

    def __gotoVistaVerificaAbbonamento(self) -> None:
        pass

    def __gotoVistaInserisciDatiCliente(self) -> None:
        pass

    def __onTariffaBoxChanged(self) -> None:
        pass

    def __onTipoBigliettoChanged(self) -> None:
        pass

    def connettiEventi(self) -> None:
        self.view.getPreviousButton().mouseReleaseEvent = lambda _: self.__gotoPrevious()
        self.view.getCercaGuidaButton().clicked.connect(self.__gotoVistaTurniGuide)
        self.view.getVerificaAbbonamentoButton().clicked.connect(self.__gotoVistaVerificaAbbonamento)
        self.view.getConfermaButton().clicked.connect(self.__gotoVistaInserisciDatiCliente)
        self.view.getTariffaComboBox().currentTextChanged.connect(self.__onTariffaBoxChanged)
        self.view.getTipoBigliettoComboBox().currentTextChanged.connect(self.__onTipoBigliettoChanged)

    def update(self) -> None:
        self.view.getCostoLabel()#TODO
