#######################################################
# 
# ControllerAggiungiOpera.py
# Python implementation of the Class ControllerAggiungiOpera
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
import RichiestaDonazione
from frontend.controller.controller import Controller
from frontend.view import VistaAggiungiOpera
import StrategyAggiungiOpera

class ControllerAggiungiOpera(Controller):
    m_VistaAggiungiOpera= VistaAggiungiOpera()

    m_StrategyAggiungiOpera= StrategyAggiungiOpera()

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self,view : VistaAggiungiOpera, previous : Controller, strategy : StrategyAggiungiOpera):
        pass

    def __onAggiungiUbicaioneClicked(self) -> None:
        pass

    def __onDropZoneDropped(self) -> None:
        pass

    def __onDropZoneClicked(self) -> None:
        pass

    def __onConfermaClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def getRichiestaDonazione(self) -> RichiestaDonazione:
        pass

    def getOpera(self) -> Opera:
        pass