#######################################################
# 
# ControllerHomeReception.py
# Python implementation of the Class ControllerHomeReception
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import Controller
import Dipendente
from frontend.view import VistaHomeReception

class ControllerHomeReception(Controller):
    def __gotoVistaAccount(self) -> None:
        pass

    def __gotoVistaVistaAcquistoBiglietto(self) -> None:
        pass

    def create(view : VistaHomeReception, home : Controller):
        pass

    def __gotoVistaVistaConvalidaBiglietto(self) -> None:
        pass

    def __gotoVistaRicercaOpera(self) -> None:
        pass

    def __gotoVistaEffettuaDonazione(self) -> None:
        pass

    def __connettiEventi(self) -> None:
        pass

class ControllerHomeReception(Controller):
    m_VistaHomeReception= VistaHomeReception()

    def __gotoVistaAccount(self) -> None:
        pass

    def __gotoVistaVistaAcquistoBiglietto(self) -> None:
        pass

    def create(view : VistaHomeReception, home : Controller, account : Dipendente):
        pass

    def __gotoVistaVistaConvalidaBiglietto(self) -> None:
        pass

    def __gotoVistaRicercaOpera(self) -> None:
        pass

    def __gotoVistaEffettuaDonazione(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass