#######################################################
# 
# ControllerVistaOpera.py
# Python implementation of the Class ControllerVistaOpera
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import Opera
from frontend.controller.controller import Controller
from frontend.view import VistaOpera

class ControllerVistaOpera(Controller):
    m_VistaOpera= VistaOpera()

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self,view : VistaOpera, previous : Controller, model : Opera):
        pass

    def connettiEventi(self) -> None:
        pass

    def __onCambiaUbicazioneClicked(self) -> None:
        pass