#######################################################
# 
# ControllerInsericiUbicazione.py
# Python implementation of the Class ControllerInsericiUbicazione
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import Ubicazione
from frontend.controller.controller import Controller
from frontend.view import VistaInsericiUbicazione

class ControllerInsericiUbicazione(Controller):
    m_VistaInsericiUbicazione= VistaInsericiUbicazione()

    def __gotoPrevious(self) -> None:
        pass

    def create(view : VistaInsericiUbicazione, previous : Controller, model : Ubicazione):
        pass

    def __onConfermaClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass