#######################################################
# 
# ControllerAcquistoBiglietto.py
# Python implementation of the Class ControllerAcquistoBiglietto
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
import Biglietto
from frontend.controller.controller import Controller
from frontend.view import VistaAcquistoBiglietto

class ControllerAcquistoBiglietto(Controller):
    m_VistaAcquistoBiglietto= VistaAcquistoBiglietto()

    def __gotoPrevious(self) -> None:
        pass

    def create(view : VistaAcquistoBiglietto, previous : Controller, model : Biglietto):
        pass

    def __gotoVistaTurniGuide(self) -> None:
        pass

    def __gotoVistaVerificaAbbonamento(self) -> None:
        pass

    def __gotoVistaInserisciDatiCliente(self) -> None:
        pass

    def __onTariffaBoxChanged(self) -> None:
        pass

    def __onTipoBigliettoChanged(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def __subscribeView(self) -> None:
        pass

    def getModel(self) -> Biglietto:
        pass

    def updatetime(self) -> None:
        pass