#######################################################
# 
# ControllerInserisciDatiCliente.py
# Python implementation of the Class ControllerInserisciDatiCliente
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import Visitatore
from frontend.controller.controller import Controller
from frontend.view import VistaInserisciDatiCliente

class ControllerInserisciDatiCliente(Controller):
    m_VistaInserisciDatiCliente= VistaInserisciDatiCliente()

    def __gotoPrevious(self) -> None:
        pass

    def create(view : VistaInserisciDatiCliente, previous : Controller, model : Visitatore):
        pass

    def __onConfermaClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass