#######################################################
# 
# ControllerTurniGuide.py
# Python implementation of the Class ControllerTurniGuide
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
from backend.high_level.museo import Museo
from frontend.controller.controller import Controller
from frontend.controller.reception.strategy_turni_guide.strategy_turni_guide import StrategyTurniGuide
from frontend.controller.reception.widget.controller_widget_turno_guida import ControllerWidgetTurnoGuida
from frontend.view.reception.vista_turni_guide import VistaTurniGuide


class ControllerTurniGuide(Controller):

    def gotoPrevious(self) -> None:
        pass

    def __init__(self, view: VistaTurniGuide, previous: Controller, model: Museo, strategy: StrategyTurniGuide):
        super().__init__(view)

    def gotoVistaModificaTurnoGuida(self) -> None:
        pass

    def __onFrecciaSinistraClicked(self) -> None:
        pass

    def __onFrecciaDestraClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def __renderizzaTurniGuida(self) -> list[ControllerWidgetTurnoGuida]:
        pass

    def initializeUi(strategy : StrategyTurniGuide) -> None:
        pass