#######################################################
# 
# ControllerRicercaOpera.py
# Python implementation of the Class ControllerRicercaOpera
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
from backend.high_level.museo import Museo
from frontend.controller.controller import Controller
from frontend.controller.reception.strategy_ricerca_opera.strategy_ricerca_opera import StrategyRicercaOpera
from frontend.view.reception.vista_ricerca_opera import VistaRicercaOpera


class ControllerRicercaOpera(Controller):

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self, view: VistaRicercaOpera, previous: Controller, model: Museo, strategy: StrategyRicercaOpera):
        super().__init__(view)

    def __onRicercaClicked(self) -> None:
        pass

    def __gotoVistaOpera(self) -> None:
        pass

    def __onOperaClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def initializeUi(self) -> None:
        pass