#######################################################
# 
# Composizione.py
# Python implementation of the Class Composizione
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
import TipoOpera

class Composizione:
    m_TipoOpera= TipoOpera()

    def __init__(self,altezzaCm : float, larghezzaCm : float, profonditaCm : float, pesoGr : float, tipo : TipoOpera):
        pass

    def calcolaArea(self) -> float:
        pass

    def calcolaVolume(self) -> float:
        pass

    def getAltezzaCm(self) -> float:
        pass

    def getLarghezzaCm(self) -> float:
        pass

    def getProfonditaCm(self) -> float:
        pass

    def getPesoGr(self) -> float:
        pass

    def getTipo(self) -> TipoOpera:
        pass