#######################################################
# 
# Evento.py
# Python implementation of the Class Evento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################


class Evento:
    def __init__(self,dataInizio : datetimetime, dataFine : datetimetime) -> None:
        pass

    def getDataInizio(self) -> datetimetime:
        pass

    def getDataFine(self) -> datetimetime:
        pass

    def getDataPianificazione(self) -> datetimetime:
        pass