#######################################################
# 
# Evento.py
# Python implementation of the Class Evento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
from datetime import datetime


class Evento:
    def __init__(self, dataInizio: datetime, dataFine: datetime) -> None:
        self.data_inizio = dataInizio
        self.data_fine = dataFine
        self.data_pianificazione = datetime.now()
