#######################################################
# 
# Mostra.py
# Python implementation of the Class Mostra
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
from datetime import datetime
from PIL.Image import Image

from backend.high_level.gestione_interna.enum.periodo_storico import PeriodoStorico
from backend.high_level.gestione_interna.evento import Evento


class Mostra(Evento):

    def __init__(self, dataInizio: datetime, dataFine: datetime, titolo: str, descrizione: str, tema: PeriodoStorico,
                 pamphlet: Image = None):
        super().__init__(dataInizio, dataFine)
        self.titolo = titolo
        self.descrizione = descrizione
        self.tema = tema
        self.pamphlet = pamphlet
