#######################################################
# 
# Mostra.py
# Python implementation of the Class Mostra
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
from datetime import datetime

from backend.high_level.gestione_interna.enum.periodo_storico import PeriodoStorico
from backend.high_level.gestione_interna.evento import Evento

class Mostra(Evento):

    def __init__(self, dataInizio: datetime, dataFine: datetime, titolo: str, descrizione: str, tema: PeriodoStorico,
                 pamphlet: PilImage):
        super().__init__(dataInizio, dataFine)

    def getTitolo(self) -> str:

        pass

    def getDescrizione(self) -> str:
        pass

    def getTema(self) -> PeriodoStorico:
        pass

    def getPamphlet(self) -> Canvas:
        pass

    def setPamphlet(newVal : Canvas) -> None:
        pass