#######################################################
# 
# Opera.py
# Python implementation of the Class Opera
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import datetime

from PIL.Image import Image

from backend.high_level.gestione_interna.composizione import Composizione
from backend.high_level.gestione_interna.enum.periodo_storico import PeriodoStorico
from backend.high_level.gestione_interna.enum.reparto_museo import RepartoMuseo
from backend.high_level.gestione_interna.ubicazione import Ubicazione
from backend.low_level.pagamenti.pagamento import Pagamento


class Opera:

    def __init__(self, autore: str = '', titolo: str = '',
                 descrizione: str = '', immagine: Image | None = None,
                 periodo: PeriodoStorico = PeriodoStorico.PREISTORIA,
                 reparto: RepartoMuseo = RepartoMuseo.MOSTRA, costo: float = 0,
                 composizione: Composizione = Composizione(),
                 ubicazione: Ubicazione = Ubicazione()):
        self.autore = autore
        self.titolo = titolo
        self.descrizione = descrizione
        self.immagine = immagine
        self.periodo = periodo
        self.reparto = reparto
        self.costo = costo
        self.composizione = composizione
        self.ubicazione = ubicazione
        self.data_inserimento = datetime.datetime.now()
        self.data_vendita = None
        self.data_acquisto = None

    def vendi(self, pagamento: Pagamento) -> bool:
        if not self.isVendibile():
            return False
        if not pagamento.paga(costo=self.costo):
            return False
        self.data_vendita = datetime.datetime.now()
        return True

    def isVendibile(self):
        return self.reparto == RepartoMuseo.MOSTRA and not self.isVenduta()

    def isVenduta(self) -> bool:
        return self.data_vendita is not None

    def isAcquistata(self) -> bool:
        return self.data_acquisto is not None
