#######################################################
# 
# TurnoGuida.py
# Python implementation of the Class TurnoGuida
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
import RepartoMuseo
import Evento

class TurnoGuida(Evento):
    m_RepartoMuseo= RepartoMuseo()

    def create(dataInizio : datetimetime, dataFine : datetimetime, reparto : RepartoMuseo, capienza : int, numeroPrenotati : int):
        pass

    def isPieno(self) -> bool:
        pass

    def isTerminato(self) -> bool:
        pass

    def getReparto(self) -> RepartoMuseo:
        pass

    def getCapienza(self) -> int:
        pass

    def getNumeroPrenotati(self) -> int:
        pass