#######################################################
# 
# TurnoGuida.py
# Python implementation of the Class TurnoGuida
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from datetime import datetime

from backend.high_level.gestione_interna.enum.reparto_museo import RepartoMuseo
from backend.high_level.gestione_interna.evento import Evento
from backend.high_level.personale.operatore_al_pubblico import OperatoreAlPubblico


class TurnoGuida(Evento):

    def __init__(self, dataInizio: datetime, dataFine: datetime, reparto: RepartoMuseo, capienza: int,
                 numeroPrenotati: int = 0):
        super().__init__(dataInizio, dataFine)
        self.durata = (dataFine - dataInizio).seconds / 60
        self.reparto: RepartoMuseo = reparto
        self.capienza = capienza
        self.numero_prenotati = numeroPrenotati
        self.guida: OperatoreAlPubblico | None = None

    def isPieno(self) -> bool:
        return self.numero_prenotati >= self.capienza

    def isTerminato(self) -> bool:
        return datetime.now() > self.data_fine
