#######################################################
# 
# Ubicazione.py
# Python implementation of the Class Ubicazione
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################


class Ubicazione:
    def __init__(self,piano : int, numeroMagazzino : int, scaffale : str, posizione : int):
        self.piano=piano
        self.numero_magazzino=numeroMagazzino
        self.scaffale=scaffale
        self.posizione=posizione


