#######################################################
# 
# Ubicazione.py
# Python implementation of the Class Ubicazione
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################


class Ubicazione:
    def __init__(self,piano : int, numeroMagazzino : int, scaffale : str, posizione : int):
        pass

    def getPiano(self) -> int:
        pass

    def getNumeroMagazzino(self) -> int:
        pass

    def getScaffale(self) -> str:
        pass

    def getPosizione(self) -> int:
        pass