#######################################################
# 
# Ubicazione.py
# Python implementation of the Class Ubicazione
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################


class Ubicazione:
    def __init__(self, piano: int = 0, numeroMagazzino: int = 0, scaffale: int = 0, posizione: int = 0):
        self.piano = piano
        self.numero_magazzino = numeroMagazzino
        self.scaffale = scaffale
        self.posizione = posizione
