#######################################################
# 
# WidgetRichiestaDonazione.py
# Python implementation of the Class WidgetRichiestaDonazione
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QWidget, QLabel, QPushButton

from frontend.view.my_widget import MyWidget


class WidgetRichiestaDonazione(MyWidget):
    def getIcon(self) -> QLabel:
        pass

    def getTitoloLabel(self) -> QLabel:
        pass

    def getEmailLabel(self) -> QLabel:
        pass

    def getRifiutaButton(self) -> QPushButton:
        pass

    def getAccettaButton(self) -> QPushButton:
        pass