#######################################################
# 
# ControllerWidgetTurnoGuida.py
# Python implementation of the Class ControllerWidgetTurnoGuida
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import TurnoGuida
import Biglietto
import WidgetTurnoGuida
import StrategyTurnoGuida
from frontend.controller.controller import Controller

class ControllerWidgetTurnoGuida(Controller):
    m_StrategyTurnoGuida= StrategyTurnoGuida()

    m_WidgetTurnoGuida= WidgetTurnoGuida()

    def create(view : WidgetTurnoGuida, model : TurnoGuida, biglietto : Biglietto):
        pass

    def __onSelezionaClicked(self) -> None:
        pass

    def __onRimuoviButton(self) -> None:
        pass

    def __onModificaButton(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def initializeUi(strategy : StrategyTurnoGuida) -> None:
        pass