#######################################################
#
# ControllerWidgetTurnoGuida.py
# Python implementation of the Class ControllerWidgetOpera
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
#
#######################################################
from PyQt5.QtGui import QPixmap

from backend.high_level.clientela.biglietto import Biglietto
from backend.high_level.gestione_interna.opera import Opera
from backend.high_level.gestione_interna.turno_guida import TurnoGuida
from frontend.controller.controller import Controller
from frontend.controller.reception.strategy_turni_guide.strategy_turni_guide import StrategyTurniGuide
from frontend.view.reception.widget.widget_opera import WidgetOpera
from frontend.view.reception.widget.widget_turno_guida import WidgetTurnoGuida


class ControllerWidgetOpera(Controller):

    def __init__(self, view: WidgetOpera, parent: Controller, model: Opera):
        super().__init__(view)
        self.view: WidgetOpera = view
        self.parent = parent
        self.model = model

    def connettiEventi(self) -> None:
        pass

    def initializeUi(self) -> None:
        self.view.getOperaLabel().setPixmap(QPixmap(":/#TODO"))  # TODO
