#######################################################
# 
# WidgetBackup.py
# Python implementation of the Class WidgetBackup
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
import QWidget

class WidgetBackup(QWidget):
    def getDataLabel(self) -> QLabel:
        pass

    def getUploadedIcon(self) -> QLabel:
        pass

    def getIcon(self) -> QLabel:
        pass

    def getEliminaButton(self) -> QPushButton:
        pass

    def getDownUpButton(self) -> QPushButton:
        pass