#######################################################
# 
# WidgetDipendente.py
# Python implementation of the Class WidgetDipendente
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QWidget, QLabel, QPushButton

from frontend.ui.location import UI_DIR
from frontend.view.my_main_window import MyMainWindow


class WidgetDipendente(MyMainWindow):
    def __init__(self):
        super().__init__(UI_DIR + '/ListViewTemplate.ui')

    def getWidget(self) -> QWidget:
        return self.selezionaDipendenteWidget

    def getNomeLabel(self) -> QLabel:
        return self.getWidget().nomeLabel

    def getIcon(self) -> QLabel:
        return self.getWidget().iconLabel

    def getLicenziaButton(self) -> QPushButton:
        return self.getWidget().licenziaButton

    def getPromuoviButton(self) -> QPushButton:
        return self.getWidget().promuoviButton
