#######################################################
# 
# WidgetPostoLavoro.py
# Python implementation of the Class WidgetPostoLavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
import QWidget

class WidgetPostoLavoro(QWidget):
    def getNomeLabel(self) -> QLabel:
        pass

    def getIcon(self) -> QLabel:
        pass

    def getPostiDisponibiliLabel(self) -> QLabel:
        pass

    def getAssegnaPostoButton(self) -> QPushButton:
        pass

    def getRimuoviButton(self) -> QPushButton:
        pass

    def getModificaButton(self) -> QPushButton:
        pass