#######################################################
# 
# WidgetBackup.py
# Python implementation of the Class WidgetBackup
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QWidget, QLabel, QPushButton

from frontend.ui.location import UI_DIR
from frontend.view.my_widget import MyWidget


class WidgetBackup(MyWidget):


    def __init__(self, parent):
        super().__init__(UI_DIR + '/BackupWidget.ui', parent)

    def getDataLabel(self) -> QLabel:
        return self.dataLabel

    def getUploadedIcon(self) -> QLabel:
        return self.cloudLabel

    def getDownloadedIcon(self) -> QLabel:
        return self.localLabel

    def getIcon(self) -> QLabel:
        return self.iconLabel

    def getEliminaButton(self) -> QPushButton:
        return self.eliminaButton

    def getDownUpButton(self) -> QPushButton:
        return self.downloadButton

    def getSizeLabel(self)->QLabel:
        return self.sizeLabel