#######################################################
# 
# WidgetPostoLavoro.py
# Python implementation of the Class WidgetPostoLavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QLabel, QPushButton

from frontend.ui.location import UI_DIR
from frontend.view.my_widget import MyWidget


class WidgetPostoLavoro(MyWidget):
    def __init__(self, parent):
        super().__init__(UI_DIR + '/gestisciPostoWidget.ui', parent)

    def getIcon(self) -> QLabel:
        return self.iconLabel

    def getPostiLiberiLabel(self) -> QLabel:
        return self.postiLiberiLabel

    def getAssegnaPostoButton(self) -> QPushButton:
        return self.assegnaButton

    def getRimuoviButton(self) -> QPushButton:
        return self.rimuoviButton

    def getModificaButton(self) -> QPushButton:
        return self.modificaButton

    def getNomeLabel(self) -> QLabel:
        return self.titoloLabel
