#######################################################
# 
# WidgetDipendente.py
# Python implementation of the Class WidgetDipendente
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
import QWidget

class WidgetDipendente(QWidget):
    def create(nome : String, lavoro : String):
        pass

    def __onLicenziaClicked(self) -> None:
        pass

    def __onPromuoviClicked(self) -> None:
        pass

class WidgetDipendente(QWidget):
    def getNomeLabel(self) -> QLabel:
        pass

    def getThumbnailIcon(self) -> QLabel:
        pass

    def getLicenziaButton(self) -> QPushButton:
        pass

    def getPromuoviButton(self) -> QPushButton:
        pass