#######################################################
# 
# Amministratore.py
# Python implementation of the Class Amministratore
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
import Lavoro

class Amministratore(Lavoro):
    def __init__(self,contratto : Canvas, stipendio : float, fondatore : bool = false):
        pass

    def isFonadatore(self) -> bool:
        pass

    def setFonadatore(newVal : bool) -> None:
        pass