#######################################################
# 
# Amministrazione.py
# Python implementation of the Class Amministrazione
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
import Amministratore
import PostoLavoro

class Amministrazione(PostoLavoro):
    m_Amministratore= Amministratore()

    def create(piano : int, numPostazioni : int, descrizione : str = ""):
        pass

    def getListaLavori(self) -> Amministratore []:
        pass