#######################################################
# 
# Credenziale.py
# Python implementation of the Class Credenziale
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import Hashing

class Credenziale:
    def verifica(password : str) -> bool:
        pass

    def getUsername(self) -> str:
        pass

    def setUsername(newVal : str) -> None:
        pass

    def __init__(self,username : str, password : str, hashing : Hashing):
        pass