#######################################################
# 
# Credenziale.py
# Python implementation of the Class Credenziale
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
from backend.low_level.sicurezza.hashing import Hashing


class Credenziale:

    def __init__(self, username: str, password: str, hashing: Hashing):
        self.username = username
        self.hashing: Hashing = hashing
        self.enc_password = self.hashing.hash(password)

    def verifica(self, password: str) -> bool:
        return password== self.enc_password
