#######################################################
# 
# Dipendente.py
# Python implementation of the Class Dipendente
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import datetime
import datetime
import Credenziale
import Lavoro
import Autentificabile

class Dipendente(Autentificabile):
    m_Credenziale= Credenziale()

    m_Lavoro= Lavoro()

    def autentifica(username : str, enc_password : str) -> bool:
        pass

    def calcolaEta(self) -> int:
        pass

    def __init__(self,nome : str, cognome : str, sesso : Sesso = Sesso.nonSpecificato, dataNascita : datetime, curriculum : Canvas = None, email : str):
        pass

    def getNome(self) -> str:
        pass

    def getCognome(self) -> str:
        pass

    def getDataNascita(self) -> datetime:
        pass

    def getCurriculum(self) -> Canvas:
        pass

    def setCurriculum(newVal : Canvas) -> None:
        pass

    def getDataRegistrazione(self) -> datetime:
        pass

    def getSesso(self) -> Sesso:
        pass

    def getEmail(self) -> str:
        pass