#######################################################
# 
# Lavoro.py
# Python implementation of the Class Lavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
from datetime import datetime

class Lavoro:
    def __init__(self, stipendio : float, numPostazione : int,contratto : str=''):
        self.stipendio=stipendio
        self.numero_postazione=numPostazione
        self.contratto=contratto
        self.data_assunzione=datetime.now()
        self.licenziato=False
        self.data_licenziamento=None
        self.nota_licenziamento=''

    def licenzia(self,notaLicenziamento : str) -> None:
        if self.licenziato:
            return
        self.nota_licenziamento=notaLicenziamento
        self.data_licenziamento=datetime.now()
        self.licenziato=True
