#######################################################
# 
# Lavoro.py
# Python implementation of the Class Lavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import datetime

class Lavoro:
    def __init__(self,contratto : Canvas, stipendio : float, numPostazione : int):
        pass

    def getDataAssunzione(self) -> datetime:
        pass

    def getContratto(self) -> Canvas:
        pass

    def getStipendio(self) -> float:
        pass

    def isLicenziato(self) -> bool:
        pass

    def getDataLicenziamento(self) -> datetime:
        pass

    def getNotaLicenziamento(self) -> str:
        pass

    def licenzia(notaLicenziamento : str) -> None:
        pass

    def getNumPostazione(self) -> int:
        pass

    def setNumPostazione(newVal : int) -> None:
        pass