#######################################################
# 
# OperatoreAlPubblico.py
# Python implementation of the Class OperatoreAlPubblico
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import datetime

from backend.high_level.personale.lavoro import Lavoro


class OperatoreAlPubblico(Lavoro):

    def __init__(self, contratto: str, stipendio: float, qualificaGuida: str, numPostazione: int):
        super().__init__(stipendio, numPostazione, contratto)
        self.qualifica = qualificaGuida
        self.turni: list['TurnoGuida'] = []

    def assegna(self, nuovo_turno: 'TurnoGuida') -> bool:
        if not (esito := self.isOccupato(nuovo_turno.data_inizio, nuovo_turno.data_fine)):
            nuovo_turno.guida = self
            self.turni.append(nuovo_turno)
        return esito

    def isOccupato(self, inizio: datetime.datetime, fine: datetime.datetime) -> bool:
        for turno in self.turni:
            if (turno.data_inizio < fine) and (turno.data_fine > inizio):
                return True
        return False
