#######################################################
# 
# PostoLavoro.py
# Python implementation of the Class PostoLavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import Lavoro
import Dipendente
import GestorePostiLavoro

class PostoLavoro(GestorePostiLavoro):
    def assumi(dipendente : Dipendente) -> bool:
        pass

    def __init__(self,piano : int, numPostazioni : int, descrizione : str = ""):
        pass

    def promuovi(dipendente : Dipendente) -> bool:
        pass

    def getPiano(self) -> int:
        pass

    def licenzia(lavoro : Lavoro) -> bool:
        pass

    def getNumPostazioni(self) -> int:
        pass

    def setNumPostazioni(newVal : int) -> None:
        pass

    def getDescrizione(self) -> str:
        pass

    def setDescrizione(newVal : str) -> None:
        pass

    def getNumPostazioniOccupate(self) -> int:
        pass

    def getListaLavori(self) -> Lavoro []:
        pass

    def getLavoratori(self) -> Lavoro []:
        pass