#######################################################
# 
# PostoLavoro.py
# Python implementation of the Class PostoLavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import abc

from backend.high_level.personale.dipendente import Dipendente


class PostoLavoro(abc.ABC):
    def __init__(self, piano: int, numPostazioni: int, descrizione: str = ''):
        self.piano = piano
        self.numero_postazioni_totali = numPostazioni
        self.descrizione = descrizione
        self.lavori = []

    @abc.abstractmethod
    def assumi(self, dipendente: Dipendente) -> bool:
        pass

    def licenzia(self, dipendente: Dipendente, notaLicensiamento: str) -> bool:
        for lavoro in self.lavori:
            if lavoro is dipendente.lavoro:
                self.lavori.remove(lavoro)
                dipendente.licenzia(notaLicensiamento)
                return True
        return False
