#######################################################
# 
# Reception.py
# Python implementation of the Class Reception
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import OperatoreAlPubblico
import PostoLavoro

class Reception(PostoLavoro):
    m_OperatoreAlPubblico= OperatoreAlPubblico()

    def __init__(self,piano : int, numPostazioni : int, numPOS : int, descrizione : str = ""):
        pass

    def getNumPos(self) -> int:
        pass

    def setNumPos(newVal : int) -> None:
        pass

    def getListaLavori(self) -> OperatoreAlPubblico []:
        pass