#######################################################
# 
# Reception.py
# Python implementation of the Class Reception
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import random

from backend.high_level.personale.dipendente import Dipendente
from backend.high_level.personale.operatore_al_pubblico import OperatoreAlPubblico
from backend.high_level.personale.posto_lavoro import PostoLavoro


class Reception(PostoLavoro):

    def __init__(self, piano: int, numPostazioni: int, numPOS: int, descrizione: str = ""):
        super().__init__(piano, numPostazioni, descrizione)
        """
        Le postcondizioni riguardanti l'attributo 'lavori' della classe reception, sottoclasse di PostoLavoro,
        sono aumentate, ma non le precondizioni.
        """
        self.numero_point_of_sales = numPOS
        self.lavori: list[OperatoreAlPubblico] = []

    def assumi(self, dipendente: Dipendente) -> bool:
        lavoro = OperatoreAlPubblico(
            contratto='contratto a tempo indeterminato',
            stipendio=max(800.0, random.gauss(1500, 300)),
            qualificaGuida='livello base',
            numPostazione=len(self.lavori) + 1
        )
        if esito := dipendente.assumi(lavoro=lavoro):
            self.lavori.append(lavoro)
        return esito
