#######################################################
# 
# Segreteria.py
# Python implementation of the Class Segreteria
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import Segretario
import RichiestaDonazione
import PostoLavoro

class Segreteria(PostoLavoro):
    m_Segretario= Segretario()

    m_RichiestaDonazione= RichiestaDonazione()

    def create(piano : int, numPostazioni : int, descr : str = "", sportelli : int):
        pass

    def getListaLavori(self) -> None:
        pass

    def getListaLavori(self) -> Segretario []:
        pass