#######################################################
# 
# Segretario.py
# Python implementation of the Class Segretario
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:00
# Original author: ValerioMorelli
# 
#######################################################
import Lavoro

class Segretario(Lavoro):
    def __init__(self,contratto : Canvas, stipendio : float):
        pass

    def getSportelloAssegnato(self) -> int:
        pass

    def setSportelloAssegnato(newVal : int) -> None:
        pass