#######################################################
# 
# StrategyWidgetDipendente.py
# Python implementation of the Interface StrategyWidgetDipendente
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################


class StrategyWidgetDipendente:
    def initializeUi(c : 'ControllerWidgetDipendente') -> None:
        pass