#######################################################
# 
# StrategyWidgetGestisciPosto.py
# Python implementation of the Class StrategyWidgetGestisciPosto
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import ControllerWidgetDipendente
import StrategyWidgetDipendente

class StrategyWidgetGestisciPosto(StrategyWidgetDipendente):
    def initializeUi(c : ControllerWidgetDipendente) -> None:
        pass

    def initializeUi(c : ControllerWidgetDipendente) -> None:
        pass