#######################################################
# 
# VistaAssumi.py
# Python implementation of the Class VistaAssumi
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLineEdit, QComboBox, QListView

from frontend.ui.location import UI_DIR
from frontend.view.my_main_window import MyMainWindow


class VistaAssumi(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/VistaAssumi.ui')

    def getPreviousButton(self) -> QPushButton:
        return self.previousButton

    def getNomeLineEdit(self) -> QLineEdit:
        return self.nomeLineEdit

    def getCognomeLineEdit(self) -> QLineEdit:
        return self.cognomeLineEdit

    def getDataNascitaLineEdit(self) -> QLineEdit:
        return self.dataNascitaLineEdit

    def getSessoComboBox(self) -> QComboBox:
        return self.sessoComboBox

    def getImpiegoComboBox(self) -> QComboBox:
        return self.impiegoComboBox

    def getPostiLavoroListView(self) -> QListView:
        return self.postiLavoroListView

    def getConfermaButton(self) -> QPushButton:
        return self.confermaButton