#######################################################
# 
# VistaModificaTurnoGuida.py
# Python implementation of the Class VistaModificaTurnoGuida
# Generated by Enterprise Architect
# Created on:      12-ott-2022 18:38:32
# Original author: MrPio
#
#######################################################
from PyQt5.QtWidgets import QPushButton, QLineEdit, QComboBox

from frontend.view.my_main_window import MyMainWindow


class VistaModificaTurnoGuida(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/ModificaTurnoGuida')

    def getPreviousButton(self) -> QPushButton:
        pass

    def getCambiaButton(self) -> QPushButton:
        pass

    def getCapienzaLineEdit(self) -> QLineEdit:
        pass

    def getOraInizioLineEdit(self) -> QLineEdit:
        pass

    def getDurataComboBox(self) -> QComboBox:
        pass
