#######################################################
# 
# VistaAllestisciMostra.py
# Python implementation of the Class VistaAllestisciMostra
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel, QLineEdit, QComboBox
from frontend.view.my_main_window import MyMainWindow


class VistaAllestisciMostra(MyMainWindow):
    def getPreviousButton(self) -> QPushButton:
        pass

    def getTitoloLineEdit(self) -> QLineEdit:
        pass

    def getPeriodoStoricoComboBox(self) -> QComboBox:
        pass

    def getDurataLineEdit(self) -> QLineEdit:
        pass

    def getListaOpere(self) -> list[QLabel]:
        pass