#######################################################
# 
# VistaAcquistoOpere.py
# Python implementation of the Class VistaAcquistoOpere
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel
from frontend.view.my_main_window import MyMainWindow
from ui.location import ROOT_DIR

class VistaAcquistoOpere(MyMainWindow):
    def getPreviousButton(self) -> QPushButton:
        pass

    def getRicercaSulWebButton(self) -> QPushButton:
        pass

    def getInserisciManualmenteButton(self) -> QPushButton:
        pass