#######################################################
# 
# VistaAssumi.py
# Python implementation of the Class VistaAssumi
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton
from frontend.view.my_main_window import MyMainWindow


class VistaAssumi(MyMainWindow):
    def __gotoPrevious(self) -> None:
        pass

    def __init__(self,previous : QMainWindow):
        pass

    def __onConfermaClicked(self) -> None:
        pass

class VistaAssumi(MyMainWindow):
    def getPreviousButton(self) -> QPushButton:
        pass

    def getNomeLineEdit(self) -> QLineEdit:
        pass

    def getCognomeLineEdit(self) -> QLineEdit:
        pass

    def getDataNascitaLineEdit(self) -> QLineEdit:
        pass

    def getSessoComboBox(self) -> QComboBox:
        pass

    def getImpiegoComboBox(self) -> QComboBox:
        pass

    def getPostiLavoroListView(self) -> QListView:
        pass

    def getConfermaButton(self) -> QPushButton:
        pass