#######################################################
# 
# VistaHomeAmministrazione.py
# Python implementation of the Class VistaHomeAmministrazione
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel
from frontend.view.my_main_window import MyMainWindow


class VistaHomeAmministrazione(MyMainWindow):
    def getAccountIcon(self) -> QLabel:
        pass

    def getGestisciDipendentiButton(self) -> QPushButton:
        pass

    def getGestisciStruttureButton(self) -> QPushButton:
        pass

    def getGestisciTurniGuideButton(self) -> QPushButton:
        pass

    def getGestisciMostreButton(self) -> QPushButton:
        pass

    def getVisualizzaStatisticheButton(self) -> QPushButton:
        pass

    def getVisualizzaReportIncassi(self) -> QPushButton:
        pass

    def getAcquistaOpereButton(self) -> QPushButton:
        pass

    def getGestisciBackupsButton(self) -> QPushButton:
        pass