#######################################################
# 
# VistaReportIncassi.py
# Python implementation of the Class VistaReportIncassi
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLineEdit, QLabel

from frontend.view.my_main_window import MyMainWindow


class VistaReportIncassi(MyMainWindow):
    def getPreviousButton(self) -> QPushButton:
        pass

    def getMeseLineEdit(self) -> QLineEdit:
        pass

    def getVisualizzaButton(self) -> QPushButton:
        pass

    def getAcquistoOpereLabel(self) -> QLabel:
        pass

    def getVenditaOpereLabel(self) -> QLabel:
        pass

    def getAbbonamentiLabel(self) -> QLabel:
        pass

    def getBigliettiLabel(self) -> QLabel:
        pass

    def getRisultatoLabel(self) -> QLabel:
        pass