#######################################################
# 
# VistaStatistiche.py
# Python implementation of the Class VistaStatistiche
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QLineEdit, QLabel, QPushButton, QCheckBox
from frontend.view.my_main_window import MyMainWindow


class VistaStatistiche(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/VistaStatistiche')

    def getPreviousButton(self) -> QPushButton:
        return self.previousButton

    def getMeseLineEdit(self) -> QLineEdit:
        return self.meseLineEdit

    def getProvenienzaCheckBox(self) -> QCheckBox:
        return self.provenienzaCheckBox

    def getEtaCheckBox(self) -> QCheckBox:
        return self.etaCheckBox

    def getSessoCheckBox(self) -> QCheckBox:
        return self.sessoCheckBox

    def getVisualizzaButton(self) -> QPushButton:
        return self.visualizzaButton

    def getRightArrowIcon(self) -> QLabel:
        return self.rightArrowIcon

    def getLeftArrowIcon(self) -> QLabel:
        return self.leftArrowIcon
