#######################################################
# 
# VistaHomeAmministrazione.py
# Python implementation of the Class VistaHomeAmministrazione
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel

from frontend.ui.location import UI_DIR
from frontend.view.my_main_window import MyMainWindow


class VistaHomeAmministrazione(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/HomeAmministrazione.ui')

    def getAccountIcon(self) -> QLabel:
        return self.accountButton

    def getGestisciDipendentiButton(self) -> QLabel:
        return self.gestisciDipendentiBigButton

    def getGestisciStruttureButton(self) -> QLabel:
        return self.gestisciStruttureBigButton

    def getGestisciTurniGuideButton(self) -> QLabel:
        return self.gestisciTurniGuideBigButton

    def getGestisciMostreButton(self) -> QLabel:
        return self.gestisciMostreBigButton

    def getVisualizzaStatisticheButton(self) -> QLabel:
        return self.visualizzaStatisticheBigButton

    def getVisualizzaReportIncassi(self) -> QLabel:
        return self.visualizzaReportIncassiBigButton

    def getAcquistaOpereButton(self) -> QLabel:
        return self.acquistaOpereBigButton

    def getGestisciBackupsButton(self) -> QPushButton:
        return self.gestisciBackupBigButton
