#######################################################
# 
# VistaGestionePostiLavoro.py
# Python implementation of the Class VistaGestionePostiLavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QListView
from frontend.view.my_main_window import MyMainWindow


class VistaGestionePostiLavoro(MyMainWindow):
    def getPreviousButton(self) -> QPushButton:
        pass

    def getReceptionsListView(self) -> QListView:
        pass

    def getSegreterieListView(self) -> QListView:
        pass

    def getAmministrazioniListView(self) -> QListView:
        pass