#######################################################
# 
# VistaModificaTurnoGuida.py
# Python implementation of the Class VistaModificaTurnoGuida
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton
from frontend.view.my_main_window import MyMainWindow


class VistaModificaTurnoGuida(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/ModificaTurnoGuida')

    def getPreviousButton(self) -> QPushButton:
        return self.previousButton

    def getCambiaButton(self) -> QPushButton:
        return self.cambiaButton

    def getCapienzaLineEdit(self) -> QLineEdit:
        pass

    def getOraInizioLineEdit(self) -> QLineEdit:
        pass

    def getDurataComboBox(self) -> QComboBox:
        return self.durataComboBox