#######################################################
# 
# VistaModificaPostoLavoro.py
# Python implementation of the Class VistaModificaPostoLavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel
from frontend.view.my_main_window import MyMainWindow
from ui.location import ROOT_DIR

class VistaModificaPostoLavoro(MyMainWindow):
    def getPreviousButton(self) -> QPushButton:
        pass

    def getNomeLineEdit(self) -> QLineEdit:
        pass

    def getPianoLineEdit(self) -> QLineEdit:
        pass

    def getCapienzaLineEdit(self) -> QLineEdit:
        pass

    def getConfermaButton(self) -> QPushButton:
        pass