#######################################################
# 
# VistaStatistiche.py
# Python implementation of the Class VistaStatistiche
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QLineEdit, QLabel, QPushButton, QFrame

from frontend.ui.location import UI_DIR
from frontend.view.my_main_window import MyMainWindow


class VistaStatistiche(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/VistaStatistiche.ui')

    def getPreviousButton(self) -> QPushButton:
        return self.previousButton

    def getMeseLineEdit(self) -> QLineEdit:
        return self.meseLineEdit

    def getProvenienzaCheckBox(self) -> QPushButton:
        return self.provenienzaCheckBox

    def getEtaCheckBox(self) -> QPushButton:
        return self.etaCheckBox

    def getSessoCheckBox(self) -> QPushButton:
        return self.sessoCheckBox

    def getVisualizzaButton(self) -> QPushButton:
        return self.visualizzaButton

    def getVisualizzaStatisticheFrame(self) -> QFrame:
        return self.visualizzaStatisticheFrame

    def getRightArrowIcon(self) -> QLabel:
        return self.rightArrowIcon

    def getLeftArrowIcon(self) -> QLabel:
        return self.leftArrowIcon

    def getNumeroVisitatoriLabel(self) -> QLabel:
        return self.numeroVisitatoriLabel

    def getPercentualeAbbonatiLabel(self) -> QLabel:
        return self.percentualeAbbonatiLabel
