#######################################################
# 
# VistaModificaPostoLavoro.py
# Python implementation of the Class VistaModificaPostoLavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLineEdit, QSpinBox

from frontend.ui.location import UI_DIR
from frontend.view.my_main_window import MyMainWindow


class VistaModificaPostoLavoro(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/ModificaPostoLavoro.ui')

    def getPreviousButton(self) -> QPushButton:
        return self.previousButton

    def getNomeLineEdit(self) -> QLineEdit:
        return self.nomeLineEdit

    def getPianoSpinBox(self) -> QSpinBox:
        return self.pianoSpinBox

    def getCapienzaSpinBox(self) -> QSpinBox:
        return self.capienzaSpinBox

    def getConfermaButton(self) -> QPushButton:
        return self.confermaButton