#######################################################
# 
# VistaAcquistoOpere.py
# Python implementation of the Class VistaAcquistoOpere
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton

from frontend.ui.location import UI_DIR
from frontend.view.my_main_window import MyMainWindow


class VistaAcquistoOpere(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/AcquistaOpera.ui')

    def getPreviousButton(self) -> QPushButton:
        return self.previousButton

    def getRicercaSulWebButton(self) -> QPushButton:
        return self.ricercaSulWebBigButton

    def getInserisciManualmenteButton(self) -> QPushButton:
        return self.inserisciManualmenteBigButton
