#######################################################
# 
# VistaBackups.py
# Python implementation of the Class VistaBackups
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QListView, QLabel

from frontend.ui.location import UI_DIR
from frontend.view.my_main_window import MyMainWindow


class VistaBackups(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/VistaBackup.ui')

    def getPreviousButton(self) -> QPushButton:
        return self.previousButton

    def getBackupsListView(self) -> QListView:
        return self.backupsListView

    def getBackupOraButton(self) -> QPushButton:
        return self.backupOraButton

    def getRefreshLabel(self) -> QLabel:
        return self.refreshLabel