#######################################################
# 
# VistaModificaPostoLavoro.py
# Python implementation of the Class VistaModificaPostoLavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton
from frontend.view.my_main_window import MyMainWindow


class VistaModificaPostoLavoro(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/ModificaPostoLavoro')

    def getPreviousButton(self) -> QPushButton:
        return self.previousButton

    def getNomeLineEdit(self) -> QLineEdit:
        return self.nomeLineEdit

    def getPianoLineEdit(self) -> QLineEdit:
        pass

    def getCapienzaLineEdit(self) -> QLineEdit:
        pass

    def getConfermaButton(self) -> QPushButton:
        return self.confermaButton