#######################################################
# 
# VistaHomeReception.py
# Python implementation of the Class VistaHomeReception
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel
from frontend.view.my_main_window import MyMainWindow
from ui.location import ROOT_DIR

class VistaHomeReception(MyMainWindow):
    def getAccountIcon(self) -> QLabel:
        pass

    def getAcquistoBigliettoButton(self) -> QPushButton:
        pass

    def getConvalidaBigliettoButton(self) -> QPushButton:
        pass

    def getVendiOperaButton(self) -> QPushButton:
        pass

    def getEffettuaDonazioneButton(self) -> QPushButton:
        pass