#######################################################
# 
# VistaInserisciDatiCliente.py
# Python implementation of the Class VistaInserisciDatiCliente
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton
from frontend.view.my_main_window import MyMainWindow


class VistaInserisciDatiCliente(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/InserisciDatiCliente.ui')

    def getPreviousButton(self) -> QPushButton:
        return self.previousButton

    def getProvenienzaLineEdit(self) -> QLineEdit:
        return self.provenienzaLineEdit

    def getDataNascitaLineEdit(self) -> QLineEdit:
        return self.dataNascitaLineEdit

    def getSessoComboBox(self) -> QComboBox:
        return self.sessoComboBox

    def getConfermaButton(self) -> QPushButton:
        return self.confermaButton