#######################################################
# 
# VistaInserisciDatiCliente.py
# Python implementation of the Class VistaInserisciDatiCliente
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton
from frontend.view.my_main_window import MyMainWindow


class VistaInserisciDatiCliente(MyMainWindow):
    def getPreviousButton(self) -> QPushButton:
        pass

    def getProvenienzaLineEdit(self) -> QLineEdit:
        pass

    def getDataNascitaLineEdit(self) -> QLineEdit:
        pass

    def getSessoComboBox(self) -> QComboBox:
        pass

    def getConfermaButton(self) -> QPushButton:
        pass