#######################################################
# 
# VistaRicercaOpera.py
# Python implementation of the Class VistaRicercaOpera
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel
from frontend.view.my_main_window import MyMainWindow
from ui.location import ROOT_DIR

class VistaRicercaOpera(MyMainWindow):
    def getHeaderLabel(self) -> QLabel:
        pass

    def getPreviousButton(self) -> QPushButton:
        pass

    def getParametroRicercaLineEdit(self) -> QLineEdit:
        pass

    def getTipoRicercaComboBox(self) -> QComboBox:
        pass

    def getRicercaButton(self) -> QPushButton:
        pass

    def getRisultatiListView(self) -> QListView:
        pass