#######################################################
# 
# VistaTurniGuide.py
# Python implementation of the Class VistaTurniGuide
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel
from frontend.view.my_main_window import MyMainWindow


class VistaTurniGuide(MyMainWindow):
    def getHeaderLabel(self) -> QLabel:
        pass

    def getPreviousButton(self) -> QPushButton:
        pass

    def getDataLineEdit(self) -> QLineEdit:
        pass

    def getRicercaButton(self) -> QPushButton:
        pass

    def getFrecciaSinistra(self) -> QLabel:
        pass

    def getFrecciaDestra(self) -> QLabel:
        pass

    def getTurniGuideListView(self) -> QListView:
        pass