#######################################################
# 
# VistaAggiungiOpera.py
# Python implementation of the Class VistaAggiungiOpera
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel
from frontend.view.my_main_window import MyMainWindow
from ui.location import ROOT_DIR

class VistaAggiungiOpera(MyMainWindow):
    def getPreviousButton(self) -> QPushButton:
        pass

    def getTitloloLineEdit(self) -> QLineEdit:
        pass

    def getAutoreLineEdit(self) -> QLineEdit:
        pass

    def getDimensioniLineEdit(self) -> QLineEdit:
        pass

    def getPeriodoStoricoComboBox(self) -> QComboBox:
        pass

    def getUbicazioneButton(self) -> QPushButton:
        pass

    def getFotoLabel(self) -> QLabel:
        pass

    def getDropZoneLabel(self) -> QLabel:
        pass

    def getConfermaButton(self) -> QPushButton:
        pass