#######################################################
# 
# ControllerBackup.py
# Python implementation of the Class ControllerBackup
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
from backend.high_level.museo import Museo
from frontend.controller.controller import Controller
from frontend.view.amministrazione.widget.widget_backup import WidgetBackup


class ControllerWidgetBackup(Controller):

    def __init__(self,view : WidgetBackup, model : Museo, parent : Controller):
        pass

    def __onDownUpButtonClicked(self) -> None:
        pass

    def __onEliminaClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def initializeUi(self):
        pass