#######################################################
# 
# ControllerWidgetDipendente.py
# Python implementation of the Class ControllerWidgetPostoLavoro
# Generated by Enterprise Architect
# Created on:      07-ott-2022 20:29:22
# Original author: MrPio
# 
#######################################################
from PyQt5.QtGui import QPixmap

from backend.high_level.personale import posto_lavoro
from backend.high_level.personale.amministrazione import Amministrazione
from backend.high_level.personale.posto_lavoro import PostoLavoro
from backend.high_level.personale.reception import Reception
from backend.high_level.personale.segreteria import Segreteria
from frontend.controller.amministrazione.widget.strategy_widget_dipendente.strategy_widget_posto_lavoro import \
    StrategyWidgetPostoLavoro
from frontend.controller.controller import Controller
from frontend.view.amministrazione.widget.widget_posto_lavoro import WidgetPostoLavoro


class ControllerWidgetPostoLavoro(Controller):

    def __init__(self, view: WidgetPostoLavoro, model: PostoLavoro, parent: Controller,
                 strategy: StrategyWidgetPostoLavoro):
        super().__init__(view)
        self.view: WidgetPostoLavoro = view
        self.model = model
        self.parent = parent
        self.strategy = strategy
        self.initializeUi()

    def __onAssegnaPostoClicked(self) -> None:
        self.parent.lavoro_scelto=self.model

    def __onRimuoviClicked(self) -> None:
        pass

    def __gotoVistaModificaPostoLavoro(self) -> None:
        pass

    def connettiEventi(self) -> None:
        self.view.getAssegnaPostoButton().clicked.connect(self.__onAssegnaPostoClicked)
        self.view.getRimuoviButton().clicked.connect(self.__onRimuoviClicked)
        self.view.getModificaButton().clicked.connect(self.__gotoVistaModificaPostoLavoro)

    def initializeUi(self):
        self.strategy.initializeUi(self)
        self.view.getNomeLabel().setText('{} (piano {})'.format(self.model.nome, self.model.piano))

        pixmaps = {
            Reception: QPixmap(":/icons/theater_comedy_FILL1_wght500_GRAD200_opsz48_risultato.png"),
            Segreteria: QPixmap(":/icons/fax_FILL1_wght500_GRAD200_opsz48_risultato.png"),
            Amministrazione: QPixmap(":/icons/shield_FILL1_wght500_GRAD200_opsz48_risultato"),
            None: QPixmap(":/icons/person_FILL1_wght600_GRAD200_opsz48_risultato"),
        }
        self.view.getIcon().setPixmap(pixmaps[type(self.model)])
