#######################################################
# 
# ControllerBackup.py
# Python implementation of the Class ControllerBackup
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
import WidgetBackup
from frontend.controller.controller import Controller

class ControllerBackup(Controller):
    m_WidgetBackup= WidgetBackup()

    def create(view : WidgetBackup, model : Backup, parent : Controller):
        pass

    def __onDownUpButtonClicked(self) -> None:
        pass

    def __onEliminaClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def initializeUi():
        pass