#######################################################
# 
# ControllerWidgetAggiungiAllaLista.py
# Python implementation of the Class ControllerWidgetAggiungiAllaLista
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import StrategyAggiungiAllaLista
import WidgetAggiungiAllaLista
from frontend.controller.controller import Controller

class ControllerWidgetAggiungiAllaLista(Controller):
    m_WidgetAggiungiAllaLista= WidgetAggiungiAllaLista()

    m_StrategyAggiungiAllaLista= StrategyAggiungiAllaLista()

    def create(view : WidgetAggiungiAllaLista, parent : Controller, strategy : StrategyAggiungiAllaLista, tipo : String =  ""):
        pass

    def __onClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def initializeUi():
        pass