#######################################################
# 
# ControllerWidgetAggiungiAllaLista.py
# Python implementation of the Class ControllerWidgetAggiungiAllaLista
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.amministrazione.widget.strategy_aggiungi_alla_lista.strategy_aggiungi_alla_lista import \
    StrategyAggiungiAllaLista
from frontend.controller.controller import Controller
from frontend.view.amministrazione.widget.widget_aggiungi_alla_lista import WidgetAggiungiAllaLista


class ControllerWidgetAggiungiAllaLista(Controller):

    def __init__(self, view: WidgetAggiungiAllaLista, parent: Controller,
                 strategy: StrategyAggiungiAllaLista, tipo: str = ""):
        super().__init__(view)
        self.view: WidgetAggiungiAllaLista = view
        self.parent = parent
        self.strategy = strategy
        self.strategy.controller=self
        self.tipo = tipo
        self.initializeUi()
        self.connettiEventi()

    def __onClicked(self) -> None:
        self.strategy.onClicked()

    def connettiEventi(self) -> None:
        self.view.getIcon().mouseReleaseEvent = lambda _: self.__onClicked()

    def initializeUi(self):
        self.view.getIcon().setPixmap(self.strategy.getIcon())
