#######################################################
# 
# ControllerWidgetDipendente.py
# Python implementation of the Class ControllerWidgetDipendente
# Generated by Enterprise Architect
# Created on:      12-ott-2022 19:37:25
# Original author: MrPio
#
#######################################################
from types import NoneType

from PyQt5.QtGui import QPixmap

from backend.high_level.personale.amministratore import Amministratore
from backend.high_level.personale.dipendente import Dipendente
from backend.high_level.personale.operatore_al_pubblico import OperatoreAlPubblico
from backend.high_level.personale.segretario import Segretario
from frontend.controller.controller import Controller
from frontend.ui.location import UI_DIR
from frontend.view.amministrazione.widget.widget_dipendente import WidgetDipendente


class ControllerWidgetDipendente(Controller):

    def __init__(self, view: WidgetDipendente, model: Dipendente):
        super().__init__(view)
        self.view: WidgetDipendente = view
        self.model = model
        self.initializeUi()

    def __onLicenziaClicked(self) -> None:
        pass  # TODO

    def __onPromuoviClicked(self) -> None:
        pass  # TODO

    def connettiEventi(self) -> None:
        self.view.getLicenziaButton().clicked.connect(self.__onLicenziaClicked)
        self.view.getPromuoviButton().clicked.connect(self.__onPromuoviClicked)

    def initializeUi(self):
        self.view.getNomeLabel().setText('{} {}'.format(self.model.nome, self.model.cognome))
        pixmaps = {
            OperatoreAlPubblico: QPixmap(":/icons/theater_comedy_FILL1_wght500_GRAD200_opsz48_risultato.png"),
            Segretario: QPixmap(":/icons/fax_FILL1_wght500_GRAD200_opsz48_risultato.png"),
            Amministratore: QPixmap(":/icons/shield_FILL1_wght500_GRAD200_opsz48_risultato"),
            NoneType: QPixmap(":/icons/person_FILL1_wght600_GRAD200_opsz48_risultato"),
        }
        self.view.getIcon().setPixmap(pixmaps[type(self.model.lavoro)])
        if type(self.model.lavoro) == Amministratore:
            self.view.getPromuoviButton().setStyleSheet(open(UI_DIR + '/css/grayButton.css', 'r').read())
            self.view.getPromuoviButton().setEnabled(False)
        if self.model.autogenerato:
            self.view.getLicenziaButton().setStyleSheet(open(UI_DIR + '/css/grayButton.css', 'r').read())
            self.view.getLicenziaButton().setEnabled(False)
        else:
            self.view.getLicenziaButton().setStyleSheet(open(UI_DIR + '/css/redButton.css', 'r').read())
