#######################################################
# 
# ControllerAcquistoAbbonamento.py
# Python implementation of the Class ControllerAcquistoAbbonamento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
import Abbonamento
from frontend.controller.controller import Controller
from frontend.view import VistaAcquistoAbbonamento

class ControllerAcquistoAbbonamento(Controller):
    m_VistaAcquistoAbbonamento= VistaAcquistoAbbonamento()

    def __gotoPrevious(self) -> None:
        pass

    def create(view : VistaAcquistoAbbonamento, previous : Controller, model : Abbonamento):
        pass

    def __onConfermaClicked(self) -> None:
        pass

    def __onDurataChanged(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def __subscribeView(self) -> None:
        pass

    def updatetime(self) -> None:
        pass