#######################################################
# 
# ControllerVistaAbbonamento.py
# Python implementation of the Class ControllerVistaAbbonamento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import datetime
import os
import tempfile

from PyQt5.QtGui import QImage, QPixmap

from backend.high_level.clientela.abbonamento import Abbonamento
from backend.high_level.clientela.cliente import Cliente
from backend.high_level.museo import Museo
from frontend.controller.controller import Controller
from frontend.view.segreteria.vista_abbonamento import VistaAbbonamento


class ControllerVistaAbbonamento(Controller):

    def __gotoPrevious(self) -> None:
        self.closeView()
        self.previous.enableView()

    def __init__(self, view: VistaAbbonamento, previous: Controller, model: Abbonamento):
        super().__init__(view)
        self.view: VistaAbbonamento = view
        self.previous = previous
        self.model = model
        self.previous.disableView()
        self.connettiEventi()
        self.initializeUi()
        self.showView()

    def connettiEventi(self) -> None:
        super().connettiEventi()
        self.view.getPreviousButton().mouseReleaseEvent = lambda _: self.__gotoPrevious()
        self.view.getQrCodeImage().mouseReleaseEvent = lambda _: self.__onQrCodeClicked()

    def __onQrCodeClicked(self):
        path = tempfile.gettempdir() + '/qrcode.jpg'
        self.model.qr_code.getImage().convert('RGB').save(path)
        os.startfile(path)

    def initializeUi(self) -> None:
        for cliente in Museo.getInstance().visitatori:
            if isinstance(cliente, Cliente):
                if self.model in cliente.abbonamenti:
                    self.view.getNomeLabel().setText(cliente.nome)
                    self.view.getCognomeLabel().setText(cliente.cognome)
                    self.view.getCodiceFiscaleLabel().setText(cliente.codice_fiscale)
                    data_scadenza = (self.model.data_rilascio + datetime.timedelta(days=self.model.tipo.days)) \
                        .strftime('%d/%m/%Y')
                    giorni_rimasti = self.model.giorniAllaScadenza()
                    self.view.getScadenzaLabel().setText(
                        f'{data_scadenza} ({abs(giorni_rimasti)} giorni ' + (
                            'rimasti)' if giorni_rimasti > 0 else 'fa)'))

                    i = self.model.qr_code.getImage()
                    i = i.convert("RGBA")
                    image = QImage(i.tobytes('raw', 'RGBA'), i.size[0],
                                   i.size[1], QImage.Format_RGBA8888)
                    self.view.getQrCodeImage().setPixmap(QPixmap.fromImage(image))
                    self.view.getQrCodeImage().setMargin(17)
