#######################################################
# 
# ControllerHomeSegreteria.py
# Python implementation of the Class ControllerHomeSegreteria
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import Dipendente
from frontend.controller.controller import Controller
from frontend.view import VistaHomeSegreteria

class ControllerHomeSegreteria(Controller):
    m_VistaHomeSegreteria= VistaHomeSegreteria()

    def __init__(self,view : VistaHomeSegreteria, home : Controller, account : Dipendente):
        pass

    def __gotoVistaAccount(self) -> None:
        pass

    def __gotoVistaAcquistoAbbonamento(self) -> None:
        pass

    def __gotoVistaConvalida(self) -> None:
        pass

    def __gotoVistaGestioneDonazioni(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass