#######################################################
# 
# ControllerConvalida.py
# Python implementation of the Class ControllerConvalida
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import Controller
import StrategyConvalida
from frontend.view import VistaConvalida

class ControllerConvalida(Controller):
    m_StrategyConvalida= StrategyConvalida()

    m_VistaConvalida= VistaConvalida()

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self,view : VistaConvalida, previous : Controller, strategy : StrategyConvalida):
        pass

    def __gotoVistaInserimentoManuale(self) -> None:
        pass

    def __onScannerizzaClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def initializeUi(self) -> None:
        pass

    def finalizza(id : str) -> None:
        pass