#######################################################
# 
# ControllerHomeSegreteria.py
# Python implementation of the Class ControllerHomeSegreteria
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
from backend.high_level.clientela.abbonamento import Abbonamento
from backend.high_level.museo import Museo
from backend.high_level.personale.dipendente import Dipendente
from frontend.controller.controller import Controller
from frontend.controller.controller_account import ControllerAccount
from frontend.controller.segreteria.controller_acquisto_abbonamento import ControllerAcquistoAbbonamento
from frontend.controller.segreteria.controller_convalida import ControllerConvalida
from frontend.controller.segreteria.controller_gestione_donazioni import ControllerGestioneDonazioni
from frontend.controller.segreteria.controller_rinnovo_abbonamento import ControllerRinnovoAbbonamento
from frontend.controller.segreteria.strategy_convalida.strategy_convalida_abbonamento import \
    StrategyConvalidaAbbonamento
from frontend.controller.segreteria.strategy_convalida.strategy_ricerca_abbonamento import StrategyRicercaAbbonamento
from frontend.view.segreteria.vista_acquisto_abbonamento import VistaAcquistoAbbonamento
from frontend.view.segreteria.vista_convalida import VistaConvalida
from frontend.view.segreteria.vista_gestione_donazioni import VistaGestioneDonazioni
from frontend.view.segreteria.vista_home_segreteria import VistaHomeSegreteria
from frontend.view.segreteria.vista_rinnovo_abbonamento import VistaRinnovoAbbonamento
from frontend.view.vista_account import VistaAccount


class ControllerHomeSegreteria(Controller):

    def __init__(self, view: VistaHomeSegreteria, home: Controller, dipendente: Dipendente):
        super().__init__(view)
        self.view: VistaHomeSegreteria = view
        self.home = home
        self.dipendente = dipendente

    def __gotoVistaAccount(self) -> None:
        self.next = ControllerAccount(
            view=VistaAccount(),
            previous=self,
            home=self.home,
            model=self.dipendente,
        )
        self.next.connettiEventi()
        self.next.showView()
        self.disableView()

    def __gotoVistaAcquistoAbbonamento(self) -> None:
        self.next = ControllerAcquistoAbbonamento(
            view=VistaAcquistoAbbonamento(),
            previous=self,
            model=Abbonamento(),
        )
        self.next.connettiEventi()
        self.next.showView()
        self.disableView()

    def __gotoVistaConvalida(self) -> None:
        self.next = ControllerConvalida(
            view=VistaConvalida(),
            previous=self,
            strategy=StrategyConvalidaAbbonamento(),
        )
        self.next.connettiEventi()
        self.next.showView()
        self.disableView()

    def __gotoVistaGestioneDonazioni(self) -> None:
        self.next = ControllerGestioneDonazioni(
            view=VistaGestioneDonazioni(),
            previous=self,
            model=Museo.getInstance(),
        )
        self.next.connettiEventi()
        self.next.showView()
        self.disableView()

    def __gotoVistaRinnovoAbbonamento(self) -> None:
        '''self.next = ControllerRinnovoAbbonamento(
            view=VistaRinnovoAbbonamento(),
            previous=self,
        )
        self.next.connettiEventi()
        self.next.showView()
        self.disableView()'''
        self.next = ControllerConvalida(
            view=VistaConvalida(),
            previous=self,
            strategy=StrategyRicercaAbbonamento(),
        )
        self.next.connettiEventi()
        self.next.showView()
        self.disableView()


    def connettiEventi(self) -> None:
        self.view.getAccountIcon().mouseReleaseEvent = lambda _: self.__gotoVistaAccount()
        self.view.getAcquistaAbbonamentoButton().mouseReleaseEvent = lambda _: self.__gotoVistaAcquistoAbbonamento()
        self.view.getConvalidaAbbonamentoButton().mouseReleaseEvent = lambda _: self.__gotoVistaConvalida()
        self.view.getGestisciDonazioneButton().mouseReleaseEvent = lambda _: self.__gotoVistaGestioneDonazioni()
        self.view.getRinnovoAbbonamentoButton().mouseReleaseEvent = lambda _: self.__gotoVistaRinnovoAbbonamento()
