#######################################################
# 
# ControllerRinnovoAbbonamento.py
# Python implementation of the Class ControllerRinnovoAbbonamento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
import Abbonamento
from frontend.controller.controller import Controller
from frontend.view import VistaRinnovoAbbonamento

class ControllerRinnovoAbbonamento(Controller):
    m_VistaRinnovoAbbonamento= VistaRinnovoAbbonamento()

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self,view : VistaRinnovoAbbonamento, previous : Controller, model : Abbonamento):
        pass

    def __onConfermaClicked(self) -> None:
        pass

    def __gotoVistaConvalida(self) -> None:
        pass

    def __gotoVistaAbbonamento(self) -> None:
        pass

    def __onDurataChanged(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def __subscribeView(self) -> None:
        pass

    def updatetime(self) -> None:
        pass