#######################################################
# 
# ControllerAcquistoAbbonamento.py
# Python implementation of the Class ControllerAcquistoAbbonamento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
from backend.high_level.clientela.abbonamento import Abbonamento
from frontend.controller.controller import Controller
from frontend.view.segreteria.vista_acquisto_abbonamento import VistaAcquistoAbbonamento


class ControllerAcquistoAbbonamento(Controller,Subscriber):

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self, view: VistaAcquistoAbbonamento, previous: Controller, model: Abbonamento):
        super().__init__(view)

    def __onConfermaClicked(self) -> None:
        pass

    def __onDurataChanged(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass

    def __subscribeView(self) -> None:
        self.model.subscribe(self)

    def update(self) -> None:
        self.view.getCostoLabel().setText('€ {}'.format(self.model.calcolaCosto()))