#######################################################
# 
# ControllerInserimentoManuale.py
# Python implementation of the Class ControllerInserimentoManuale
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:59
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import Controller
from frontend.view import VistaInserimentoManuale

class ControllerInserimentoManuale(Controller):
    m_VistaInserimentoManuale= VistaInserimentoManuale()

    def __gotoPrevious(self) -> None:
        pass

    def create(view : VistaInserimentoManuale, previous : Controller):
        pass

    def __onConfermaClicked(self) -> None:
        pass

    def connettiEventi(self) -> None:
        pass