#######################################################
# 
# ControllerGestioneDonazioni.py
# Python implementation of the Class ControllerGestioneDonazioni
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:39:58
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.controller import Controller
from frontend.view import VistaGestioneDonazioni
from frontend.controller.controller import ControllerWidgetRichiestaDonazione

class ControllerGestioneDonazioni(Controller):
    m_ControllerWidgetRichiestaDonazione= ControllerWidgetRichiestaDonazione()

    m_VistaGestioneDonazioni= VistaGestioneDonazioni()

    def __gotoPrevious(self) -> None:
        pass

    def __init__(self,view : VistaGestioneDonazioni, previous : Controller, model : Museo):
        pass

    def connettiEventi(self) -> None:
        pass

    def __renderizzaRichiestaDonazioni(self) -> ControllerWidgetRichiestaDonazione []:
        pass

    def initializeUi(self) -> None:
        pass