#######################################################
# 
# StrategyWidgetGestisciPosto.py
# Python implementation of the Class StrategyWidgetGestisciPosto
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.amministrazione.widget.strategy_widget_posto_lavoro.strategy_widget_posto_lavoro import \
    StrategyWidgetPostoLavoro


class StrategyWidgetGestisciPosto(StrategyWidgetPostoLavoro):
    def initializeUi(self, c: 'ControllerWidgetPostoLavoro') -> None:
        c.view.getAssegnaPostoButton().setVisible(False)
        c.view.getModificaButton().setVisible(True)
        c.view.getRimuoviButton().setVisible(True)
