#######################################################
# 
# StrategyWidgetAssegnaPosto.py
# Python implementation of the Class StrategyWidgetAssegnaPosto
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from frontend.controller.amministrazione.widget.strategy_widget_posto_lavoro.strategy_widget_posto_lavoro import \
    StrategyWidgetPostoLavoro

class StrategyWidgetAssegnaPosto(StrategyWidgetPostoLavoro):
    def initializeUi(self,c : 'ControllerWidgetPostoLavoro') -> None:
        c.view.getAssegnaPostoButton().setVisible(True)
        c.view.getModificaButton().setVisible(False)
        c.view.getRimuoviButton().setVisible(False)
