#######################################################
# 
# VistaInserimentoManuale.py
# Python implementation of the Class VistaInserimentoManuale
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton
from frontend.view.my_main_window import MyMainWindow


class VistaInserimentoManuale(MyMainWindow):
    def getPreviousButton(self) -> QPushButton:
        pass

    def getIdLineEdit(self) -> QLineEdit:
        pass