#######################################################
# 
# VistaAcquistoAbbonamento.py
# Python implementation of the Class VistaAcquistoAbbonamento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel
from frontend.view.my_main_window import MyMainWindow
from ui.location import ROOT_DIR

class VistaAcquistoAbbonamento(MyMainWindow):
    def getPreviousButton(self) -> QPushButton:
        pass

    def getNomeLineEdit(self) -> QLineEdit:
        pass

    def getCognomeLineEdit(self) -> QLineEdit:
        pass

    def getCodiceFiscaleLineEdit(self) -> QLineEdit:
        pass

    def getProvenienzaLineEdit(self) -> QLineEdit:
        pass

    def getDataNascitaLineEdit(self) -> QLineEdit:
        pass

    def getSessoComboBox(self) -> QComboBox:
        pass

    def getDurataComboBox(self) -> QComboBox:
        pass

    def getCostoLabel(self) -> QLabel:
        pass

    def getConfermaButton(self) -> QPushButton:
        pass