#######################################################
# 
# VistaConvalida.py
# Python implementation of the Class VistaConvalida
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel

from frontend.ui.location import UI_DIR
from frontend.view.my_main_window import MyMainWindow


class VistaConvalida(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/Convalida.ui')

    def getHeaderLabel(self) -> QLabel:
        return self.headerLabel

    def getPreviousButton(self) -> QPushButton:
        return self.previousButton

    def getInserisciManualmenteButton(self) -> QPushButton:
        return self.inserisciManualmenteBigButton

    def getScannerizzaButton(self) -> QPushButton:
        return self.scannerizzaBigButton
