#######################################################
# 
# VistaGestioneDonazioni.py
# Python implementation of the Class VistaGestioneDonazioni
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton
from frontend.view.my_main_window import MyMainWindow


class VistaGestioneDonazioni(MyMainWindow):
    def getPreviousButton(self) -> QPushButton:
        pass

    def getDonazioniListView(self) -> QListView:
        pass