#######################################################
# 
# VistaGestioneDonazioni.py
# Python implementation of the Class VistaGestioneDonazioni
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QListView

from frontend.ui.location import UI_DIR
from frontend.view.my_main_window import MyMainWindow


class VistaGestioneDonazioni(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR+'/VistaGestisciDonazioni.ui')

    def getPreviousButton(self) -> QPushButton:
        return self.previousButton

    def getDonazioniListView(self) -> QListView:
        return self.donazioniListView