#######################################################
# 
# VistaAbbonamento.py
# Python implementation of the Class VistaAbbonamento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel

from frontend.ui.location import UI_DIR
from frontend.view.my_main_window import MyMainWindow


class VistaAbbonamento(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/VistaAbbonamento.ui')

    def getPreviousButton(self) -> QPushButton:
        return self.previousButton

    def getNomeLabel(self) -> QLabel:
        return self.nomeLabel

    def getCognomeLabel(self) -> QLabel:
        return self.cognomeLabel

    def getCodiceFiscaleLabel(self) -> QLabel:
        return self.codiceFiscaleLabel

    def getScadenzaLabel(self) -> QLabel:
        return self.scadenzaLabel

    def getQrCodeImage(self) -> QLabel:
        return self.qrCodeImage

    def getConfermaButton(self) -> QPushButton:
        return self.confermaButton