#######################################################
# 
# VistaRinnovoAbbonamento.py
# Python implementation of the Class VistaRinnovoAbbonamento
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:02
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel, QComboBox, QFrame

from frontend.ui.location import UI_DIR
from frontend.view.my_main_window import MyMainWindow


class VistaRinnovoAbbonamento(MyMainWindow):

    def __init__(self):
        super().__init__(UI_DIR + '/RinnovaAbbonamento.ui')

    def getPreviousButton(self) -> QPushButton:
        return self.previousButton

    def getQrCodeImage(self) -> QLabel:
        return self.qrCodeImage

    def getDurataComboBox(self) -> QComboBox:
        return self.durataComboBox

    def getConfermaButton(self) -> QPushButton:
        return self.confermaButton