#######################################################
# 
# VistaConvalida.py
# Python implementation of the Class VistaConvalida
# Generated by Enterprise Architect
# Created on:      07-ott-2022 17:40:01
# Original author: ValerioMorelli
# 
#######################################################
from PyQt5.QtWidgets import QPushButton, QLabel
from frontend.view.my_main_window import MyMainWindow


class VistaConvalida(MyMainWindow):
    def getHeaderLabel(self) -> QLabel:
        pass

    def getPreviousButton(self) -> QPushButton:
        pass

    def getInserisciManualmenteButton(self) -> QPushButton:
        pass

    def getScannerizzaButton(self) -> QPushButton:
        pass